**Please enter your name and student ID here.**

**ANLY 6100 - Data Analytics I**

**Homework - Machine Learning Landscape**

Use the concepts you learned in *Machine Learning Landscape*, specifically the two regression methods (linear regression and k-nearest neighbors), to analyze the dataset provided in `population_vs_day.csv`.
In this file:

- **date** : Represents the specific date.

- **day** : The day index, where 20190101 is assumed to be Day 1, 20190102 is Day 2, and so forth.

- **population** : The population of a species, recorded in millions.

Utilize both linear regression and k-nearest neighbors to identify trends in the population data over time.

There are two options for this assignment.

### Option 1

For this assignment, you can simply run the provided code in **Q1** to get started. You do not need to download the `population_vs_day.csv` file and upload it to your Google Drive.

If you choose this option, you can skip the steps for:

* Connecting to Google Drive
* Setting the current folder

### Option 2

If you prefer, you may download the `population_vs_day.csv` file, upload it to your Google Drive, connect Google Colab to your Google Drive, and set the appropriate current folder.

This option is also acceptable. If you choose this approach, you may need to delete or modify the provided code in **Q1**.

In [ ]:
# Mount your drive
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
# Change current directory
%cd "path of the new directory"

In [ ]:
# Verify the current directory
%pwd

In [ ]:
# Verify the current directory
%ls

## Q1. (0.5 points)

Use pandas to load the dataset into a DataFrame.

<div>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>date</th>
      <th>day</th>
      <th>population</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>20190101</td>
      <td>1</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>1</th>
      <td>20190102</td>
      <td>2</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>2</th>
      <td>20190103</td>
      <td>3</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>3</th>
      <td>20190104</td>
      <td>4</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>4</th>
      <td>20190105</td>
      <td>5</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>985</th>
      <td>20210912</td>
      <td>986</td>
      <td>721.081622</td>
    </tr>
    <tr>
      <th>986</th>
      <td>20210913</td>
      <td>987</td>
      <td>721.081622</td>
    </tr>
    <tr>
      <th>987</th>
      <td>20210914</td>
      <td>988</td>
      <td>881.321983</td>
    </tr>
    <tr>
      <th>988</th>
      <td>20210915</td>
      <td>989</td>
      <td>640.961442</td>
    </tr>
    <tr>
      <th>989</th>
      <td>20210916</td>
      <td>990</td>
      <td>560.841262</td>
    </tr>
  </tbody>
</table>
<p>990 rows × 3 columns</p>
</div>

In [ ]:
# Provide your answer here.

In [ ]:
# Run the following code to start if you choose option 1.
import pandas as pd
df=pd.read_csv("https://juxinglongsuuta.github.io/anly6100/population_vs_day.csv")
df.head(5)

## Q2. (1 point)

Use `matplotlib`'s `scatter()` function to visualize the dataset.

You should get a figure similar to this one.

<img  width="600"  src=''/>

In [ ]:
# Provide your answer here.

## Q3. (0.5 points)

Use Python code to find the minimum and maximum population values.

```text
Minimum population: 0.0
Maximum population: 151667.5013
```

In [ ]:
# Provide your answer here.

## Q4. (0.5 points)

Write a few sentences describing your findings from the dataset, including details like the maximum, minimum, and population trends. Try to craft a narrative around the data.

Provide your answer here.

Your answer here

## Q5. (0.5 points)

Write Python code to get the training features `X` (the 'day' column from the dataset).

<div>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>day</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1</td>
    </tr>
    <tr>
      <th>1</th>
      <td>2</td>
    </tr>
    <tr>
      <th>2</th>
      <td>3</td>
    </tr>
    <tr>
      <th>3</th>
      <td>4</td>
    </tr>
    <tr>
      <th>4</th>
      <td>5</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
    </tr>
    <tr>
      <th>985</th>
      <td>986</td>
    </tr>
    <tr>
      <th>986</th>
      <td>987</td>
    </tr>
    <tr>
      <th>987</th>
      <td>988</td>
    </tr>
    <tr>
      <th>988</th>
      <td>989</td>
    </tr>
    <tr>
      <th>989</th>
      <td>990</td>
    </tr>
  </tbody>
</table>
<p>990 rows × 1 columns</p>
</div>

In [ ]:
# Provide your answer here.

## Q6. (0.5 points)

Write Python code to get the training target `y` (the 'population' column from the dataset).

<div>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>population</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>1</th>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>2</th>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>3</th>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>4</th>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
    </tr>
    <tr>
      <th>985</th>
      <td>721.081622</td>
    </tr>
    <tr>
      <th>986</th>
      <td>721.081622</td>
    </tr>
    <tr>
      <th>987</th>
      <td>881.321983</td>
    </tr>
    <tr>
      <th>988</th>
      <td>640.961442</td>
    </tr>
    <tr>
      <th>989</th>
      <td>560.841262</td>
    </tr>
  </tbody>
</table>
<p>990 rows × 1 columns</p>
</div>

In [ ]:
# Provide your answer here.

## Q7. (1 point)

Use `sklearn.linear_model.LinearRegression` to train a linear regression model.

In [ ]:
# Provide your answer here.

## Q8. (1 point)

Use `sklearn.neighbors.KNeighborsRegressor` to train a k-NN model.

In [ ]:
# Provide your answer here.

## Q9. (0.5 points)

Use `numpy.arange()` to generate 11 numbers: [0, 100, 200, ..., 1000]. Reshape it to (11, 1) and name it `X_test`.

```text
array([[   0],
       [ 100],
       [ 200],
       [ 300],
       [ 400],
       [ 500],
       [ 600],
       [ 700],
       [ 800],
       [ 900],
       [1000]])
```

In [ ]:
# Provide your answer here.

## Q10. (0.5 points)

Use the linear model to predict the population for the days in `X_test` using the `predict()` function.

You should get a result similar to this.

```text
array([41276.58174422, 42585.14843232, 43893.71512041, 45202.2818085,
       46510.84849659, 47819.41518468, 49127.98187277, 50436.54856086,
       51745.11524895, 53053.68193704, 54362.24862513])
```

In [ ]:
# Provide your answer here.

## Q11. (0.5 points)

Use the k-NN model to predict the population for the days in `X_test` using the `predict()` function.

You should get a result similar to this.

```text
array([     0.        ,      0.        ,   1794.692038  ,  36518.778166  ,
        98595.893836  , 145257.88682   , 123224.83724   ,  53728.592888  ,
        12418.62794   ,    833.2498748 ,    705.05758638])
```

In [ ]:
# Provide your answer here.

## Q12. (2 points)

Visualize the results on the figure using `scatter()`.

You should get a result similar to this.

<img  width="600"  src=''/>

In [ ]:
# Provide your answer here.

## Q13. (0.5 points)

Write a few sentences to comment on the results.

Provide your answer here.

## Q14. (0.5 points)

Can you think of ways to improve the linear model? Write a few sentences to explain your answer.

Provide your answer here.