In [ ]:
# ctrl v to paste
%cd "/content/drive/MyDrive/Colab Notebooks/0ANLY2500SP26/LC/L18"

/content/drive/MyDrive/Colab Notebooks/0ANLY2500SP26/LC/L18

In [ ]:
%ls

D1.csv  L18_LCP.ipynb  us-cities-top-1k.csv

In [ ]:
%pwd

'/content/drive/MyDrive/Colab Notebooks/0ANLY2500SP26/LC/L18'

In [ ]:
import pandas as pd

In [ ]:
df= pd.read_csv("us-cities-top-1k.csv") # ctrl c to copy
print(df)

              City           State  Population        lat         lon
0       Marysville      Washington       63269  48.051764 -122.177082
1           Perris      California       72326  33.782519 -117.228648
2        Cleveland            Ohio      390113  41.499320  -81.694361
3        Worcester   Massachusetts      182544  42.262593  -71.802293
4         Columbia  South Carolina      133358  34.000710  -81.034814
..             ...             ...         ...        ...         ...
995  West New York      New Jersey       52122  40.787879  -74.014306
996        Everett   Massachusetts       42935  42.408430  -71.053663
997         Linden      New Jersey       41301  40.622048  -74.244590
998      Asheville  North Carolina       87236  35.595058  -82.551487
999        Compton      California       97877  33.895849 -118.220071

[1000 rows x 5 columns]

In [ ]:
l=[2]*1000
print(l)

[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]

In [ ]:
df["NC1"]=l

In [ ]:
print(df)

              City           State  Population        lat         lon  NC1
0       Marysville      Washington       63269  48.051764 -122.177082    2
1           Perris      California       72326  33.782519 -117.228648    2
2        Cleveland            Ohio      390113  41.499320  -81.694361    2
3        Worcester   Massachusetts      182544  42.262593  -71.802293    2
4         Columbia  South Carolina      133358  34.000710  -81.034814    2
..             ...             ...         ...        ...         ...  ...
995  West New York      New Jersey       52122  40.787879  -74.014306    2
996        Everett   Massachusetts       42935  42.408430  -71.053663    2
997         Linden      New Jersey       41301  40.622048  -74.244590    2
998      Asheville  North Carolina       87236  35.595058  -82.551487    2
999        Compton      California       97877  33.895849 -118.220071    2

[1000 rows x 6 columns]

In [ ]:
df["NC2"]=df["Population"]*1.03

In [ ]:
print(df)

              City           State  Population        lat         lon  NC1  \
0       Marysville      Washington       63269  48.051764 -122.177082    2
1           Perris      California       72326  33.782519 -117.228648    2
2        Cleveland            Ohio      390113  41.499320  -81.694361    2
3        Worcester   Massachusetts      182544  42.262593  -71.802293    2
4         Columbia  South Carolina      133358  34.000710  -81.034814    2
..             ...             ...         ...        ...         ...  ...
995  West New York      New Jersey       52122  40.787879  -74.014306    2
996        Everett   Massachusetts       42935  42.408430  -71.053663    2
997         Linden      New Jersey       41301  40.622048  -74.244590    2
998      Asheville  North Carolina       87236  35.595058  -82.551487    2
999        Compton      California       97877  33.895849 -118.220071    2

           NC2
0     65167.07
1     74495.78
2    401816.39
3    188020.32
4    137358.74
..         ...
995   53685.66
996   44223.05
997   42540.03
998   89853.08
999  100813.31

[1000 rows x 7 columns]

In [ ]:
df.to_csv("D1.csv",index=False)

In [ ]:
%ls

D1.csv  L18_LCP.ipynb  us-cities-top-1k.csv

In [ ]:
# pandas
%pwd

'/content/drive/MyDrive/Colab Notebooks/0ANLY2500SP26/LC/L18'

In [ ]:
%ls

D1.csv  L18.ipynb  us-cities-top-1k.csv  uscity.csv

In [ ]:
import pandas as pd
mdf=pd.read_csv("uscity.csv") # RAM
#print(mdf)
mdf
# dataframe
# series
# head() tail()
# columns, single column
# sort
# filtering
# group by

,id,city,county,state,population,lat,lng,stateid
0,1840034016,New York,Queens,New York,19268388,40.6943,-73.9249,NY
1,1840020491,Los Angeles,Los Angeles,California,11984083,34.1141,-118.4068,CA
2,1840000494,Chicago,Cook,Illinois,8609571,41.8375,-87.6866,IL
3,1840015149,Miami,Miami-Dade,Florida,6391670,25.7840,-80.2101,FL
4,1840020925,Houston,Harris,Texas,6227666,29.7860,-95.3885,TX
...,...,...,...,...,...,...,...,...
31252,1840025878,Santa Cruz,Pinal,Arizona,0,33.2327,-112.1594,AZ
31253,1840153017,Frankstown,Blair,Pennsylvania,0,40.4444,-78.3558,PA
31254,1840153026,Ski Gap,Blair,Pennsylvania,0,40.3160,-78.5174,PA
31255,1840153079,Sherman,Western Connecticut,Connecticut,0,41.5746,-73.4957,CT
31256,1840153147,Twin Lakes,Mono,California,0,38.1695,-119.3422,CA

In [ ]:
a=10 # RAM
b=20
#print(a)
#print(a)
#print(a)
a #
b

20

In [ ]:
mdf # print(mdf)
# dataframe:table (2D)
# bool, int, double: simple
# [2,3,4]: list, collection, [] walls, warehouse
# series: single row or single column in df
# 1D

,id,city,county,state,population,lat,lng,stateid
0,1840034016,New York,Queens,New York,19268388,40.6943,-73.9249,NY
1,1840020491,Los Angeles,Los Angeles,California,11984083,34.1141,-118.4068,CA
2,1840000494,Chicago,Cook,Illinois,8609571,41.8375,-87.6866,IL
3,1840015149,Miami,Miami-Dade,Florida,6391670,25.7840,-80.2101,FL
4,1840020925,Houston,Harris,Texas,6227666,29.7860,-95.3885,TX
...,...,...,...,...,...,...,...,...
31252,1840025878,Santa Cruz,Pinal,Arizona,0,33.2327,-112.1594,AZ
31253,1840153017,Frankstown,Blair,Pennsylvania,0,40.4444,-78.3558,PA
31254,1840153026,Ski Gap,Blair,Pennsylvania,0,40.3160,-78.5174,PA
31255,1840153079,Sherman,Western Connecticut,Connecticut,0,41.5746,-73.4957,CT
31256,1840153147,Twin Lakes,Mono,California,0,38.1695,-119.3422,CA

In [ ]:
# head() tail()
# random.randint()
df1=mdf.head(3) # Tom's his, result in a new df,
df1 # print(df1)

,id,city,county,state,population,lat,lng,stateid
0,1840034016,New York,Queens,New York,19268388,40.6943,-73.9249,NY
1,1840020491,Los Angeles,Los Angeles,California,11984083,34.1141,-118.4068,CA
2,1840000494,Chicago,Cook,Illinois,8609571,41.8375,-87.6866,IL

In [ ]:
# read_csv() vs to_csv()
# save the dataframe from RAM to hard drive
df1.to_csv("f3.csv",index=True) #
df1.to_csv("f3_.csv",index=False)

In [ ]:
mdf

,id,city,county,state,population,lat,lng,stateid
0,1840034016,New York,Queens,New York,19268388,40.6943,-73.9249,NY
1,1840020491,Los Angeles,Los Angeles,California,11984083,34.1141,-118.4068,CA
2,1840000494,Chicago,Cook,Illinois,8609571,41.8375,-87.6866,IL
3,1840015149,Miami,Miami-Dade,Florida,6391670,25.7840,-80.2101,FL
4,1840020925,Houston,Harris,Texas,6227666,29.7860,-95.3885,TX
...,...,...,...,...,...,...,...,...
31252,1840025878,Santa Cruz,Pinal,Arizona,0,33.2327,-112.1594,AZ
31253,1840153017,Frankstown,Blair,Pennsylvania,0,40.4444,-78.3558,PA
31254,1840153026,Ski Gap,Blair,Pennsylvania,0,40.3160,-78.5174,PA
31255,1840153079,Sherman,Western Connecticut,Connecticut,0,41.5746,-73.4957,CT
31256,1840153147,Twin Lakes,Mono,California,0,38.1695,-119.3422,CA

In [ ]:
cs=mdf.columns # get all column names
print(cs)

Index(['id', 'city', 'county', 'state', 'population', 'lat', 'lng', 'stateid'], dtype='object')

In [ ]:
# []: walls or boundary of a warehouse
# [2,3,3]
# mdf[] : . indexer operator
mdf['population'] # get a signle column from a df, series

0        19268388
1        11984083
2         8609571
3         6391670
4         6227666
           ...
31252           0
31253           0
31254           0
31255           0
31256           0
Name: population, Length: 31257, dtype: int64

In [ ]:
mdf["NC"]=[2]*31257
mdf["NC"]=mdf["population"]*1.03
mdf

,id,city,county,state,population,lat,lng,stateid,NC
0,1840034016,New York,Queens,New York,19268388,40.6943,-73.9249,NY,19846439.64
1,1840020491,Los Angeles,Los Angeles,California,11984083,34.1141,-118.4068,CA,12343605.49
2,1840000494,Chicago,Cook,Illinois,8609571,41.8375,-87.6866,IL,8867858.13
3,1840015149,Miami,Miami-Dade,Florida,6391670,25.7840,-80.2101,FL,6583420.10
4,1840020925,Houston,Harris,Texas,6227666,29.7860,-95.3885,TX,6414495.98
...,...,...,...,...,...,...,...,...,...
31252,1840025878,Santa Cruz,Pinal,Arizona,0,33.2327,-112.1594,AZ,0.00
31253,1840153017,Frankstown,Blair,Pennsylvania,0,40.4444,-78.3558,PA,0.00
31254,1840153026,Ski Gap,Blair,Pennsylvania,0,40.3160,-78.5174,PA,0.00
31255,1840153079,Sherman,Western Connecticut,Connecticut,0,41.5746,-73.4957,CT,0.00
31256,1840153147,Twin Lakes,Mono,California,0,38.1695,-119.3422,CA,0.00

In [ ]:
mdf.to_csv("NewData.csv",index=False)

In [ ]:
%ls

D1.csv  f3_.csv    NewData.csv           uscity.csv
f3.csv  L18.ipynb  us-cities-top-1k.csv