In [ ]:
%cd "/content/drive/MyDrive/Colab Notebooks/0ANLY2500SP26/LC/L19"

/content/drive/MyDrive/Colab Notebooks/0ANLY2500SP26/LC/L19

In [ ]:
%ls

L19_LCP.ipynb  us-cities-top-1k.csv  utah.csv

In [ ]:
%pwd

'/content/drive/MyDrive/Colab Notebooks/0ANLY2500SP26/LC/L19'

In [ ]:
import pandas as pd

In [ ]:
#
df1=pd.read_csv("us-cities-top-1k.csv")

In [ ]:
df1

              City           State  Population        lat         lon
0       Marysville      Washington       63269  48.051764 -122.177082
1           Perris      California       72326  33.782519 -117.228648
2        Cleveland            Ohio      390113  41.499320  -81.694361
3        Worcester   Massachusetts      182544  42.262593  -71.802293
4         Columbia  South Carolina      133358  34.000710  -81.034814
..             ...             ...         ...        ...         ...
995  West New York      New Jersey       52122  40.787879  -74.014306
996        Everett   Massachusetts       42935  42.408430  -71.053663
997         Linden      New Jersey       41301  40.622048  -74.244590
998      Asheville  North Carolina       87236  35.595058  -82.551487
999        Compton      California       97877  33.895849 -118.220071

[1000 rows x 5 columns]

In [ ]:
# filtering
# get one single column
c1=df1["State"]=="Utah"
print(c1)

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Name: State, Length: 1000, dtype: bool

In [ ]:
df2=df1[c1]
print(df2)

                 City State  Population        lat         lon
31              Logan  Utah       48913  41.736980 -111.833836
193      South Jordan  Utah       59366  40.562170 -111.929658
285         Bountiful  Utah       43023  40.889390 -111.880771
381             Provo  Utah      116288  40.233844 -111.658534
434      Spanish Fork  Utah       36956  40.114955 -111.654923
440      Taylorsville  Utah       60519  40.667725 -111.938826
466          Riverton  Utah       40921  40.521893 -111.939102
500              Lehi  Utah       54382  40.391617 -111.850766
533             Ogden  Utah       84249  41.223000 -111.973830
568            Layton  Utah       70790  41.060222 -111.971053
603            Murray  Utah       48612  40.666892 -111.887991
630             Sandy  Utah       90231  40.564978 -111.838973
673  West Valley City  Utah      133579  40.691613 -112.001050
676              Orem  Utah       91648  40.296898 -111.694648
737               Roy  Utah       37733  41.161611 -112.026331
762            Draper  Utah       45285  40.524671 -111.863823
856        St. George  Utah       76817  37.096528 -113.568416
955       West Jordan  Utah      110077  40.609670 -111.939103
964    Salt Lake City  Utah      191180  40.760779 -111.891047

In [ ]:
df2.to_csv("utah.csv",index=False)

In [ ]:
%ls

L19_LCP.ipynb  us-cities-top-1k.csv  utah.csv

In [ ]:
%pwd

'/content/drive/MyDrive/Colab Notebooks/0ANLY2500SP26/LC/L19'

In [ ]:
%ls

L19.ipynb  us-cities-top-1k.csv  uscity.csv  utah.csv

In [ ]:
import pandas as pd
mdf=pd.read_csv("uscity.csv")
mdf
# dataframe, table, 2D
# series, 1D
# collection

,id,city,county,state,population,lat,lng,stateid
0,1840034016,New York,Queens,New York,19268388,40.6943,-73.9249,NY
1,1840020491,Los Angeles,Los Angeles,California,11984083,34.1141,-118.4068,CA
2,1840000494,Chicago,Cook,Illinois,8609571,41.8375,-87.6866,IL
3,1840015149,Miami,Miami-Dade,Florida,6391670,25.7840,-80.2101,FL
4,1840020925,Houston,Harris,Texas,6227666,29.7860,-95.3885,TX
...,...,...,...,...,...,...,...,...
31252,1840025878,Santa Cruz,Pinal,Arizona,0,33.2327,-112.1594,AZ
31253,1840153017,Frankstown,Blair,Pennsylvania,0,40.4444,-78.3558,PA
31254,1840153026,Ski Gap,Blair,Pennsylvania,0,40.3160,-78.5174,PA
31255,1840153079,Sherman,Western Connecticut,Connecticut,0,41.5746,-73.4957,CT
31256,1840153147,Twin Lakes,Mono,California,0,38.1695,-119.3422,CA

In [ ]:
# get a single column
mdf.columns

Index(['id', 'city', 'county', 'state', 'population', 'lat', 'lng', 'stateid'], dtype='object')

In [ ]:
s1=mdf["state"]
s1

0            New York
1          California
2            Illinois
3             Florida
4               Texas
             ...
31252         Arizona
31253    Pennsylvania
31254    Pennsylvania
31255     Connecticut
31256      California
Name: state, Length: 31257, dtype: object

In [ ]:
# unique() max() min() avg() value_counts()
s1=mdf["state"]
states=s1.unique()
print(states)

n=len(states)
print(n)

n1=len(s1)
print(n1)

r=s1.value_counts()
r

['New York' 'California' 'Illinois' 'Florida' 'Texas' 'Pennsylvania'
 'Georgia' 'District of Columbia' 'Massachusetts' 'Arizona' 'Michigan'
 'Washington' 'Minnesota' 'Colorado' 'Nevada' 'Maryland' 'Missouri'
 'Oregon' 'Puerto Rico' 'Indiana' 'Ohio' 'North Carolina' 'Virginia'
 'Rhode Island' 'Wisconsin' 'Tennessee' 'Utah' 'Oklahoma' 'Connecticut'
 'Kentucky' 'Louisiana' 'Nebraska' 'Alabama' 'New Mexico' 'South Carolina'
 'Iowa' 'Kansas' 'Arkansas' 'Idaho' 'New Jersey' 'Hawaii' 'Mississippi'
 'Alaska' 'New Hampshire' 'North Dakota' 'Maine' 'South Dakota'
 'West Virginia' 'Delaware' 'Montana' 'Vermont' 'Wyoming']
52
31257

state
Pennsylvania            1886
Texas                   1836
California              1598
Illinois                1456
Ohio                    1253
Missouri                1081
Iowa                    1024
Indiana                  974
New York                 970
Florida                  945
Minnesota                904
Oklahoma                 839
Wisconsin                792
North Carolina           771
Michigan                 740
Kansas                   738
Virginia                 680
Georgia                  670
New Jersey               655
Washington               633
Arkansas                 621
Nebraska                 593
Alabama                  592
Kentucky                 552
Maryland                 532
New Mexico               520
Tennessee                501
Montana                  495
Louisiana                489
South Dakota             482
Colorado                 477
South Carolina           473
Arizona                  461
West Virginia            439
Mississippi              426
Oregon                   425
North Dakota             401
Alaska                   355
Utah                     332
Puerto Rico              281
Idaho                    236
Wyoming                  204
Connecticut              185
Hawaii                   158
Nevada                   132
Massachusetts            125
Vermont                  107
Delaware                  79
Maine                     66
New Hampshire             41
Rhode Island              31
District of Columbia       1
Name: count, dtype: int64

In [ ]:
s2=mdf['city']
n=len(s2)
print(n)

r=s2.unique()
print(r)
n=len(r)
print(n)

s2.value_counts()

31257
['New York' 'Los Angeles' 'Chicago' ... 'Falcon Village' 'Frankstown'
 'Ski Gap']
20939

city
Franklin            29
Fairview            25
Clinton             24
Marion              24
Greenville          23
                    ..
Kingvale             1
Clary                1
Pistol River         1
Greenwood Colony     1
Thompson Springs     1
Name: count, Length: 20939, dtype: int64

In [ ]:
mdf.columns

Index(['id', 'city', 'county', 'state', 'population', 'lat', 'lng', 'stateid'], dtype='object')

In [ ]:
# max() min() mean() count()
s3=mdf['population']
r=s3.count()
print(r)

31257

In [ ]:
# function on dataframe
# sort_values(by=[],ascending=[])
# produce a new dataframe
df1=mdf.sort_values(by=['population'],ascending=[False])

df1.to_csv("sorted.csv",index=False)

df2=df1.head(10) # dataframe
df2.to_csv("top10.csv",index=False)

In [ ]:
%ls

L19.ipynb  sorted.csv  top10.csv  us-cities-top-1k.csv  uscity.csv  utah.csv

In [ ]:
df2

,id,city,county,state,population,lat,lng,stateid
0,1840034016,New York,Queens,New York,19268388,40.6943,-73.9249,NY
1,1840020491,Los Angeles,Los Angeles,California,11984083,34.1141,-118.4068,CA
2,1840000494,Chicago,Cook,Illinois,8609571,41.8375,-87.6866,IL
3,1840015149,Miami,Miami-Dade,Florida,6391670,25.7840,-80.2101,FL
4,1840020925,Houston,Harris,Texas,6227666,29.7860,-95.3885,TX
5,1840019440,Dallas,Dallas,Texas,5968322,32.7935,-96.7667,TX
6,1840000673,Philadelphia,Philadelphia,Pennsylvania,5782653,40.0077,-75.1339,PA
7,1840013660,Atlanta,Fulton,Georgia,5298788,33.7628,-84.4220,GA
8,1840006060,Washington,District of Columbia,District of Columbia,5230370,38.9047,-77.0163,DC
9,1840000455,Boston,Suffolk,Massachusetts,4453352,42.3188,-71.0852,MA

In [ ]:
c=df2['state']=="Texas"
print(c)
df3=df2[c] # filtering

df3.to_csv("t.csv",index=False)
df3

0    False
1    False
2    False
3    False
4     True
5     True
6    False
7    False
8    False
9    False
Name: state, dtype: bool

           id     city  county  state  population      lat      lng stateid
4  1840020925  Houston  Harris  Texas     6227666  29.7860 -95.3885      TX
5  1840019440   Dallas  Dallas  Texas     5968322  32.7935 -96.7667      TX