In [ ]:
%cd "/content/drive/MyDrive/Colab Notebooks/0ANLY2500SP26/LC/L20"

/content/drive/MyDrive/Colab Notebooks/0ANLY2500SP26/LC/L20

In [ ]:
%pwd

'/content/drive/MyDrive/Colab Notebooks/0ANLY2500SP26/LC/L20'

In [ ]:
%ls

L20.ipynb  us-cities-top-1k.csv  uscity.csv  utah.csv

In [ ]:
import pandas as pd

In [ ]:
df1=pd.read_csv("us-cities-top-1k.csv")

In [ ]:
df1

              City           State  Population        lat         lon
0       Marysville      Washington       63269  48.051764 -122.177082
1           Perris      California       72326  33.782519 -117.228648
2        Cleveland            Ohio      390113  41.499320  -81.694361
3        Worcester   Massachusetts      182544  42.262593  -71.802293
4         Columbia  South Carolina      133358  34.000710  -81.034814
..             ...             ...         ...        ...         ...
995  West New York      New Jersey       52122  40.787879  -74.014306
996        Everett   Massachusetts       42935  42.408430  -71.053663
997         Linden      New Jersey       41301  40.622048  -74.244590
998      Asheville  North Carolina       87236  35.595058  -82.551487
999        Compton      California       97877  33.895849 -118.220071

[1000 rows x 5 columns]

In [ ]:
# groupby(): divide the big table (dataframe) into small ones
df1["State"].value_counts()

State
California              212
Texas                    83
Florida                  73
Illinois                 52
Massachusetts            36
Ohio                     33
Michigan                 31
Washington               28
Arizona                  25
Minnesota                24
North Carolina           22
New Jersey               22
Colorado                 21
Indiana                  21
Wisconsin                20
Utah                     19
Georgia                  18
New York                 17
Virginia                 17
Tennessee                17
Missouri                 16
Connecticut              15
Oregon                   14
Pennsylvania             13
Iowa                     13
South Carolina           12
Alabama                  12
Oklahoma                 11
Kansas                   11
Arkansas                 10
Louisiana                 9
Idaho                     8
New Mexico                7
Maryland                  7
Mississippi               6
Rhode Island              6
Nevada                    6
Kentucky                  5
North Dakota              4
Nebraska                  4
Montana                   4
New Hampshire             3
Wyoming                   2
Delaware                  2
West Virginia             2
South Dakota              2
Maine                     1
Alaska                    1
District of Columbia      1
Hawaii                    1
Vermont                   1
Name: count, dtype: int64

In [ ]:
r=df1.groupby(by=["State"])

In [ ]:
r.groups.keys()

dict_keys(['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'District of Columbia', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming'])

In [ ]:
df2=r.get_group("Utah")

/tmp/ipykernel_231/1624792969.py:1: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  df2=r.get_group("Utah")

In [ ]:
df2

                 City State  Population        lat         lon
31              Logan  Utah       48913  41.736980 -111.833836
193      South Jordan  Utah       59366  40.562170 -111.929658
285         Bountiful  Utah       43023  40.889390 -111.880771
381             Provo  Utah      116288  40.233844 -111.658534
434      Spanish Fork  Utah       36956  40.114955 -111.654923
440      Taylorsville  Utah       60519  40.667725 -111.938826
466          Riverton  Utah       40921  40.521893 -111.939102
500              Lehi  Utah       54382  40.391617 -111.850766
533             Ogden  Utah       84249  41.223000 -111.973830
568            Layton  Utah       70790  41.060222 -111.971053
603            Murray  Utah       48612  40.666892 -111.887991
630             Sandy  Utah       90231  40.564978 -111.838973
673  West Valley City  Utah      133579  40.691613 -112.001050
676              Orem  Utah       91648  40.296898 -111.694648
737               Roy  Utah       37733  41.161611 -112.026331
762            Draper  Utah       45285  40.524671 -111.863823
856        St. George  Utah       76817  37.096528 -113.568416
955       West Jordan  Utah      110077  40.609670 -111.939103
964    Salt Lake City  Utah      191180  40.760779 -111.891047

In [ ]:
df2.to_csv("utah.csv",index=True)

In [ ]:
%ls

L20.ipynb  us-cities-top-1k.csv  uscity.csv  utah.csv

In [ ]:
%pwd

'/content/drive/MyDrive/Colab Notebooks/0ANLY2500SP26/LC/L20'

In [ ]:
%ls

L20.ipynb  us-cities-top-1k.csv  uscity.csv  utah.csv

In [ ]:
import pandas as pd
mdf=pd.read_csv("uscity.csv")
mdf # print(mdf)
# mdf: dataframe, table

,id,city,county,state,population,lat,lng,stateid
0,1840034016,New York,Queens,New York,19268388,40.6943,-73.9249,NY
1,1840020491,Los Angeles,Los Angeles,California,11984083,34.1141,-118.4068,CA
2,1840000494,Chicago,Cook,Illinois,8609571,41.8375,-87.6866,IL
3,1840015149,Miami,Miami-Dade,Florida,6391670,25.7840,-80.2101,FL
4,1840020925,Houston,Harris,Texas,6227666,29.7860,-95.3885,TX
...,...,...,...,...,...,...,...,...
31252,1840025878,Santa Cruz,Pinal,Arizona,0,33.2327,-112.1594,AZ
31253,1840153017,Frankstown,Blair,Pennsylvania,0,40.4444,-78.3558,PA
31254,1840153026,Ski Gap,Blair,Pennsylvania,0,40.3160,-78.5174,PA
31255,1840153079,Sherman,Western Connecticut,Connecticut,0,41.5746,-73.4957,CT
31256,1840153147,Twin Lakes,Mono,California,0,38.1695,-119.3422,CA

In [ ]:
df10=mdf.head(10) # new dataframe, table
df10

,id,city,county,state,population,lat,lng,stateid
0,1840034016,New York,Queens,New York,19268388,40.6943,-73.9249,NY
1,1840020491,Los Angeles,Los Angeles,California,11984083,34.1141,-118.4068,CA
2,1840000494,Chicago,Cook,Illinois,8609571,41.8375,-87.6866,IL
3,1840015149,Miami,Miami-Dade,Florida,6391670,25.7840,-80.2101,FL
4,1840020925,Houston,Harris,Texas,6227666,29.7860,-95.3885,TX
5,1840019440,Dallas,Dallas,Texas,5968322,32.7935,-96.7667,TX
6,1840000673,Philadelphia,Philadelphia,Pennsylvania,5782653,40.0077,-75.1339,PA
7,1840013660,Atlanta,Fulton,Georgia,5298788,33.7628,-84.4220,GA
8,1840006060,Washington,District of Columbia,District of Columbia,5230370,38.9047,-77.0163,DC
9,1840000455,Boston,Suffolk,Massachusetts,4453352,42.3188,-71.0852,MA

In [ ]:
# filtering: result in table
# dataframe, table vs single row, single column, series
# and: &
# or: |
# not: ~
c=df10["state"]=='Texas' # series
print(c)
ndf=df10[c] # table, dataframe
ndf

0    False
1    False
2    False
3    False
4     True
5     True
6    False
7    False
8    False
9    False
Name: state, dtype: bool

           id     city  county  state  population      lat      lng stateid
4  1840020925  Houston  Harris  Texas     6227666  29.7860 -95.3885      TX
5  1840019440   Dallas  Dallas  Texas     5968322  32.7935 -96.7667      TX

In [ ]:
#
c1=df10["state"]=="New York"
print(c1)

c2=df10["state"]=="Texas"
print(c2)

c3=df10["state"]=="Florida"
print(c3)
# & |
# &
c=c1|c2|c3 # &
print(c)
df10[c]

0     True
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
Name: state, dtype: bool
0    False
1    False
2    False
3    False
4     True
5     True
6    False
7    False
8    False
9    False
Name: state, dtype: bool
0    False
1    False
2    False
3     True
4    False
5    False
6    False
7    False
8    False
9    False
Name: state, dtype: bool
0     True
1    False
2    False
3     True
4     True
5     True
6    False
7    False
8    False
9    False
Name: state, dtype: bool

,id,city,county,state,population,lat,lng,stateid
0,1840034016,New York,Queens,New York,19268388,40.6943,-73.9249,NY
3,1840015149,Miami,Miami-Dade,Florida,6391670,25.7840,-80.2101,FL
4,1840020925,Houston,Harris,Texas,6227666,29.7860,-95.3885,TX
5,1840019440,Dallas,Dallas,Texas,5968322,32.7935,-96.7667,TX

In [ ]:
#
c1=mdf["state"]=="Texas"
c2=mdf['population']>1000000
c3=mdf['population']<6000000
c=c1&c2&c3
mdf[c]#

,id,city,county,state,population,lat,lng,stateid
5,1840019440,Dallas,Dallas,Texas,5968322,32.7935,-96.7667,TX
25,1840022220,San Antonio,Bexar,Texas,2096390,29.4632,-98.5238,TX
28,1840019590,Austin,Travis,Texas,1940039,30.3005,-97.7522,TX

In [ ]:
# Texas or Florida
c1=mdf["state"]=="Texas"
c4=mdf["state"]=="Florida"
c2=mdf['population']>1000000
c3=mdf['population']<6000000
c=(c1|c4) & c2 & c3 #
df=mdf[c]# table
df.to_csv("texas_florida_city.csv",index=False)
df

,id,city,county,state,population,lat,lng,stateid
5,1840019440,Dallas,Dallas,Texas,5968322,32.7935,-96.7667,TX
15,1840015982,Tampa,Hillsborough,Florida,2957531,27.9945,-82.4447,FL
25,1840022220,San Antonio,Bexar,Texas,2096390,29.4632,-98.5238,TX
27,1840015099,Orlando,Orange,Florida,1948155,28.4773,-81.3370,FL
28,1840019590,Austin,Travis,Texas,1940039,30.3005,-97.7522,TX
41,1840015031,Jacksonville,Duval,Florida,1335714,30.3322,-81.6749,FL

In [ ]:
%ls

L20.ipynb  texas_florida_city.csv  us-cities-top-1k.csv  uscity.csv  utah.csv