In [ ]:
%cd "/content/drive/MyDrive/Colab Notebooks/0ANLY2500SP26/LC/L21"

/content/drive/MyDrive/Colab Notebooks/0ANLY2500SP26/LC/L21

In [ ]:
%pwd

'/content/drive/MyDrive/Colab Notebooks/0ANLY2500SP26/LC/L21'

In [ ]:
%ls

L21_LCP.ipynb  sorted.csv  tips.csv  uscity.csv

In [ ]:
import pandas as pd

In [ ]:
df1=pd.read_csv("tips.csv")

In [ ]:
df1

      ID  total_bill   tip     sex smoker   day    time  size
0      1       16.99  1.01  Female     No   Sun  Dinner     2
1      2       10.34  1.66    Male     No   Sun  Dinner     3
2      3       21.01  3.50    Male     No   Sun  Dinner     3
3      4       23.68  3.31    Male     No   Sun  Dinner     2
4      5       24.59  3.61  Female     No   Sun  Dinner     4
..   ...         ...   ...     ...    ...   ...     ...   ...
239  240       29.03  5.92    Male     No   Sat  Dinner     3
240  241       27.18  2.00  Female    Yes   Sat  Dinner     2
241  242       22.67  2.00    Male    Yes   Sat  Dinner     2
242  243       17.82  1.75    Male     No   Sat  Dinner     2
243  244       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 8 columns]

In [ ]:
df1.columns

Index(['ID', 'total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [ ]:
df2=df1.sort_values(by=['total_bill',"tip"],ascending=[False,False])

In [ ]:
df2

      ID  total_bill    tip     sex smoker   day    time  size
170  171       50.81  10.00    Male    Yes   Sat  Dinner     3
212  213       48.33   9.00    Male     No   Sat  Dinner     4
59    60       48.27   6.73    Male     No   Sat  Dinner     4
156  157       48.17   5.00    Male     No   Sun  Dinner     6
182  183       45.35   3.50    Male    Yes   Sun  Dinner     3
..   ...         ...    ...     ...    ...   ...     ...   ...
149  150        7.51   2.00    Male     No  Thur   Lunch     2
172  173        7.25   5.15    Male    Yes   Sun  Dinner     2
111  112        7.25   1.00  Female     No   Sat  Dinner     1
92    93        5.75   1.00  Female    Yes   Fri  Dinner     2
67    68        3.07   1.00  Female    Yes   Sat  Dinner     1

[244 rows x 8 columns]

In [ ]:
df1

      ID  total_bill   tip     sex smoker   day    time  size
0      1       16.99  1.01  Female     No   Sun  Dinner     2
1      2       10.34  1.66    Male     No   Sun  Dinner     3
2      3       21.01  3.50    Male     No   Sun  Dinner     3
3      4       23.68  3.31    Male     No   Sun  Dinner     2
4      5       24.59  3.61  Female     No   Sun  Dinner     4
..   ...         ...   ...     ...    ...   ...     ...   ...
239  240       29.03  5.92    Male     No   Sat  Dinner     3
240  241       27.18  2.00  Female    Yes   Sat  Dinner     2
241  242       22.67  2.00    Male    Yes   Sat  Dinner     2
242  243       17.82  1.75    Male     No   Sat  Dinner     2
243  244       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 8 columns]

In [ ]:
df2.to_csv("sorted.csv",index=False)

In [ ]:
%ls

L21_LCP.ipynb  sorted.csv  tips.csv  uscity.csv

In [ ]:
%pwd

'/content/drive/MyDrive/Colab Notebooks/0ANLY2500SP26/LC/L21'

In [ ]:
%ls

L21.ipynb  sorted.csv  tips.csv  uscity.csv

In [ ]:
import pandas as pd

In [ ]:
mdf=pd.read_csv("uscity.csv")
mdf # dataframe, table

,id,city,county,state,population,lat,lng,stateid
0,1840034016,New York,Queens,New York,19268388,40.6943,-73.9249,NY
1,1840020491,Los Angeles,Los Angeles,California,11984083,34.1141,-118.4068,CA
2,1840000494,Chicago,Cook,Illinois,8609571,41.8375,-87.6866,IL
3,1840015149,Miami,Miami-Dade,Florida,6391670,25.7840,-80.2101,FL
4,1840020925,Houston,Harris,Texas,6227666,29.7860,-95.3885,TX
...,...,...,...,...,...,...,...,...
31252,1840025878,Santa Cruz,Pinal,Arizona,0,33.2327,-112.1594,AZ
31253,1840153017,Frankstown,Blair,Pennsylvania,0,40.4444,-78.3558,PA
31254,1840153026,Ski Gap,Blair,Pennsylvania,0,40.3160,-78.5174,PA
31255,1840153079,Sherman,Western Connecticut,Connecticut,0,41.5746,-73.4957,CT
31256,1840153147,Twin Lakes,Mono,California,0,38.1695,-119.3422,CA

In [ ]:
# filtering: table, dataframe
s="Texas" #"Utah"
c1 = mdf["state"]==s # series
df=mdf[c1]# new dataframe, new table
df.to_csv(f"{s}.csv",index=True)
df#print(df)

,id,city,county,state,population,lat,lng,stateid
4,1840020925,Houston,Harris,Texas,6227666,29.7860,-95.3885,TX
5,1840019440,Dallas,Dallas,Texas,5968322,32.7935,-96.7667,TX
25,1840022220,San Antonio,Bexar,Texas,2096390,29.4632,-98.5238,TX
28,1840019590,Austin,Travis,Texas,1940039,30.3005,-97.7522,TX
52,1840020696,Fort Worth,Tarrant,Texas,963194,32.7817,-97.3474,TX
...,...,...,...,...,...,...,...,...
31234,1840041593,Victoria Vera,Starr,Texas,0,26.3182,-98.6929,TX
31235,1840041577,Valle Verde,Webb,Texas,0,27.6797,-99.2010,TX
31240,1840037129,Buena Vista,Starr,Texas,0,26.2941,-98.6109,TX
31241,1840018286,Brundage,Dimmit,Texas,0,28.5739,-99.6702,TX
31251,1840018314,Falcon Village,Starr,Texas,0,26.5652,-99.1341,TX

In [ ]:
ss=mdf["state"].unique()
print(ss)

n=len(ss)# length
print(f"There are {n} states.")

['New York' 'California' 'Illinois' 'Florida' 'Texas' 'Pennsylvania'
 'Georgia' 'District of Columbia' 'Massachusetts' 'Arizona' 'Michigan'
 'Washington' 'Minnesota' 'Colorado' 'Nevada' 'Maryland' 'Missouri'
 'Oregon' 'Puerto Rico' 'Indiana' 'Ohio' 'North Carolina' 'Virginia'
 'Rhode Island' 'Wisconsin' 'Tennessee' 'Utah' 'Oklahoma' 'Connecticut'
 'Kentucky' 'Louisiana' 'Nebraska' 'Alabama' 'New Mexico' 'South Carolina'
 'Iowa' 'Kansas' 'Arkansas' 'Idaho' 'New Jersey' 'Hawaii' 'Mississippi'
 'Alaska' 'New Hampshire' 'North Dakota' 'Maine' 'South Dakota'
 'West Virginia' 'Delaware' 'Montana' 'Vermont' 'Wyoming']
There are 52 states.

In [ ]:
%ls

 Alabama.csv                 Louisiana.csv         Oregon.csv
 Alaska.csv                  Maine.csv             Pennsylvania.csv
 Arizona.csv                 Maryland.csv         'Puerto Rico.csv'
 Arkansas.csv                Massachusetts.csv    'Rhode Island.csv'
 California.csv              Michigan.csv          sorted.csv
 Colorado.csv                Minnesota.csv        'South Carolina.csv'
 Connecticut.csv             Mississippi.csv      'South Dakota.csv'
 Delaware.csv                Missouri.csv          Tennessee.csv
'District of Columbia.csv'   Montana.csv           Texas.csv
 Florida.csv                 Nebraska.csv          tips.csv
 Georgia.csv                 Nevada.csv            uscity.csv
 Hawaii.csv                 'New Hampshire.csv'    Utah.csv
 Idaho.csv                  'New Jersey.csv'       Vermont.csv
 Illinois.csv               'New Mexico.csv'       Virginia.csv
 Indiana.csv                'New York.csv'         Washington.csv
 Iowa.csv                   'North Carolina.csv'  'West Virginia.csv'
 Kansas.csv                 'North Dakota.csv'     Wisconsin.csv
 Kentucky.csv                Ohio.csv              Wyoming.csv
 L21.ipynb                   Oklahoma.csv

In [ ]:
# loop: for loop
#ss=["Texas","Utah","Maine"]
for s in ss: ## ss: collection, s: placeholder s="Texas"
  print(f"\n\nWe are processing State: {s}")
  c1=mdf["state"]==s
  df=mdf[c1]
  #df.to_csv(f"{s}.csv",index=False)
  n=len(df)
  print(f"There are {n} cities in {s}.")
  ndf=df.sort_values(by=["population"],ascending=[False])
  df1=ndf.head(1)
  print(f"The city with largest population in {s} is:")
  print(df1)
  #print(df)

We are processing State: New York
There are 970 cities in New York.
The city with largest population in New York is:
           id      city  county     state  population      lat      lng  \
0  1840034016  New York  Queens  New York    19268388  40.6943 -73.9249

  stateid
0      NY


We are processing State: California
There are 1598 cities in California.
The city with largest population in California is:
           id         city       county       state  population      lat  \
1  1840020491  Los Angeles  Los Angeles  California    11984083  34.1141

        lng stateid
1 -118.4068      CA


We are processing State: Illinois
There are 1456 cities in Illinois.
The city with largest population in Illinois is:
           id     city county     state  population      lat      lng stateid
2  1840000494  Chicago   Cook  Illinois     8609571  41.8375 -87.6866      IL


We are processing State: Florida
There are 945 cities in Florida.
The city with largest population in Florida is:
           id   city      county    state  population     lat      lng stateid
3  1840015149  Miami  Miami-Dade  Florida     6391670  25.784 -80.2101      FL


We are processing State: Texas
There are 1836 cities in Texas.
The city with largest population in Texas is:
           id     city  county  state  population     lat      lng stateid
4  1840020925  Houston  Harris  Texas     6227666  29.786 -95.3885      TX


We are processing State: Pennsylvania
There are 1886 cities in Pennsylvania.
The city with largest population in Pennsylvania is:
           id          city        county         state  population      lat  \
6  1840000673  Philadelphia  Philadelphia  Pennsylvania     5782653  40.0077

       lng stateid
6 -75.1339      PA


We are processing State: Georgia
There are 670 cities in Georgia.
The city with largest population in Georgia is:
           id     city  county    state  population      lat     lng stateid
7  1840013660  Atlanta  Fulton  Georgia     5298788  33.7628 -84.422      GA


We are processing State: District of Columbia
There are 1 cities in District of Columbia.
The city with largest population in District of Columbia is:
           id        city                county                 state  \
8  1840006060  Washington  District of Columbia  District of Columbia

   population      lat      lng stateid
8     5230370  38.9047 -77.0163      DC


We are processing State: Massachusetts
There are 125 cities in Massachusetts.
The city with largest population in Massachusetts is:
           id    city   county          state  population      lat      lng  \
9  1840000455  Boston  Suffolk  Massachusetts     4453352  42.3188 -71.0852

  stateid
9      MA


We are processing State: Arizona
There are 461 cities in Arizona.
The city with largest population in Arizona is:
            id     city    county    state  population      lat       lng  \
10  1840020568  Phoenix  Maricopa  Arizona     4121103  33.5722 -112.0892

   stateid
10      AZ


We are processing State: Michigan
There are 740 cities in Michigan.
The city with largest population in Michigan is:
            id     city county     state  population      lat      lng stateid
11  1840003971  Detroit  Wayne  Michigan     3773725  42.3834 -83.1024      MI


We are processing State: Washington
There are 633 cities in Washington.
The city with largest population in Washington is:
            id     city county       state  population      lat       lng  \
12  1840021117  Seattle   King  Washington     3642006  47.6211 -122.3244

   stateid
12      WA


We are processing State: Minnesota
There are 904 cities in Minnesota.
The city with largest population in Minnesota is:
            id         city    county      state  population      lat  \
16  1840007830  Minneapolis  Hennepin  Minnesota     2937866  44.9635

        lng stateid
16 -93.2678      MN


We are processing State: Colorado
There are 477 cities in Colorado.
The city with largest population in Colorado is:
            id    city  county     state  population     lat       lng stateid
18  1840018789  Denver  Denver  Colorado     2714768  39.762 -104.8758      CO


We are processing State: Nevada
There are 132 cities in Nevada.
The city with largest population in Nevada is:
            id       city county   state  population      lat       lng  \
21  1840020364  Las Vegas  Clark  Nevada     2299189  36.2333 -115.2654

   stateid
21      NV


We are processing State: Maryland
There are 532 cities in Maryland.
The city with largest population in Maryland is:
            id       city     county     state  population      lat      lng  \
22  1840001592  Baltimore  Baltimore  Maryland     2201673  39.3051 -76.6144

   stateid
22      MD


We are processing State: Missouri
There are 1081 cities in Missouri.
The city with largest population in Missouri is:
            id       city     county     state  population      lat      lng  \
23  1840001651  St. Louis  St. Louis  Missouri     2129918  38.6359 -90.2451

   stateid
23      MO


We are processing State: Oregon
There are 425 cities in Oregon.
The city with largest population in Oregon is:
            id      city     county   state  population      lat     lng  \
24  1840019941  Portland  Multnomah  Oregon     2115140  45.5371 -122.65

   stateid
24      OR


We are processing State: Puerto Rico
There are 281 cities in Puerto Rico.
The city with largest population in Puerto Rico is:
            id      city    county        state  population      lat     lng  \
30  1630035577  San Juan  San Juan  Puerto Rico     1813477  18.3985 -66.061

   stateid
30      PR


We are processing State: Indiana
There are 974 cities in Indiana.
The city with largest population in Indiana is:
            id          city  county    state  population      lat      lng  \
31  1840030084  Indianapolis  Marion  Indiana     1767321  39.7771 -86.1458

   stateid
31      IN


We are processing State: Ohio
There are 1253 cities in Ohio.
The city with largest population in Ohio is:
            id        city    county state  population      lat     lng  \
33  1840003814  Cincinnati  Hamilton  Ohio     1726642  39.1413 -84.506

   stateid
33      OH


We are processing State: North Carolina
There are 771 cities in North Carolina.
The city with largest population in North Carolina is:
            id       city       county           state  population      lat  \
38  1840014557  Charlotte  Mecklenburg  North Carolina     1488249  35.2083

        lng stateid
38 -80.8303      NC


We are processing State: Virginia
There are 680 cities in Virginia.
The city with largest population in Virginia is:
            id            city          county     state  population      lat  \
40  1840003871  Virginia Beach  Virginia Beach  Virginia     1441893  36.7335

        lng stateid
40 -76.0435      VA


We are processing State: Rhode Island
There are 31 cities in Rhode Island.
The city with largest population in Rhode Island is:
            id        city      county         state  population     lat  \
42  1840003289  Providence  Providence  Rhode Island     1292041  41.823

        lng stateid
42 -71.4187      RI


We are processing State: Wisconsin
There are 792 cities in Wisconsin.
The city with largest population in Wisconsin is:
            id       city     county      state  population      lat      lng  \
43  1840003046  Milwaukee  Milwaukee  Wisconsin     1291752  43.0642 -87.9675

   stateid
43      WI


We are processing State: Tennessee
There are 501 cities in Tennessee.
The city with largest population in Tennessee is:
            id       city    county      state  population      lat      lng  \
44  1840036155  Nashville  Davidson  Tennessee     1201962  36.1715 -86.7842

   stateid
44      TN


We are processing State: Utah
There are 332 cities in Utah.
The city with largest population in Utah is:
            id            city     county state  population      lat  \
45  1840021383  Salt Lake City  Salt Lake  Utah     1183003  40.7776

         lng stateid
45 -111.9311      UT


We are processing State: Oklahoma
There are 839 cities in Oklahoma.
The city with largest population in Oklahoma is:
            id           city    county     state  population      lat  \
49  1840020428  Oklahoma City  Oklahoma  Oklahoma     1017828  35.4676

        lng stateid
49 -97.5136      OK


We are processing State: Connecticut
There are 185 cities in Connecticut.
The city with largest population in Connecticut is:
            id      city   county        state  population      lat      lng  \
50  1840004773  Hartford  Capitol  Connecticut      990793  41.7661 -72.6834

   stateid
50      CT


We are processing State: Kentucky
There are 552 cities in Kentucky.
The city with largest population in Kentucky is:
            id        city     county     state  population      lat      lng  \
51  1840030815  Louisville  Jefferson  Kentucky      988018  38.1663 -85.6485

   stateid
51      KY


We are processing State: Louisiana
There are 489 cities in Louisiana.
The city with largest population in Louisiana is:
            id         city   county      state  population      lat      lng  \
55  1840001839  New Orleans  Orleans  Louisiana      928503  30.0687 -89.9288

   stateid
55      LA


We are processing State: Nebraska
There are 593 cities in Nebraska.
The city with largest population in Nebraska is:
            id   city   county     state  population      lat      lng stateid
58  1840009315  Omaha  Douglas  Nebraska      836740  41.2627 -96.0529      NE


We are processing State: Alabama
There are 592 cities in Alabama.
The city with largest population in Alabama is:
            id        city     county    state  population      lat      lng  \
60  1840006507  Birmingham  Jefferson  Alabama      773997  33.5279 -86.7971

   stateid
60      AL


We are processing State: New Mexico
There are 520 cities in New Mexico.
The city with largest population in New Mexico is:
            id         city      county       state  population      lat  \
61  1840019176  Albuquerque  Bernalillo  New Mexico      765360  35.1054

         lng stateid
61 -106.6465      NM


We are processing State: South Carolina
There are 473 cities in South Carolina.
The city with largest population in South Carolina is:
            id        city      county           state  population      lat  \
63  1840015163  Charleston  Charleston  South Carolina      734681  32.8168

        lng stateid
63 -79.9687      SC


We are processing State: Iowa
There are 1024 cities in Iowa.
The city with largest population in Iowa is:
            id        city county state  population      lat      lng stateid
78  1840007069  Des Moines   Polk  Iowa      570091  41.5725 -93.6105      IA


We are processing State: Kansas
There are 738 cities in Kansas.
The city with largest population in Kansas is:
            id     city    county   state  population      lat      lng  \
84  1840001686  Wichita  Sedgwick  Kansas      519036  37.6895 -97.3443

   stateid
84      KS


We are processing State: Arkansas
There are 621 cities in Arkansas.
The city with largest population in Arkansas is:
            id         city   county     state  population      lat      lng  \
94  1840015509  Little Rock  Pulaski  Arkansas      466334  34.7256 -92.3577

   stateid
94      AR


We are processing State: Idaho
There are 236 cities in Idaho.
The city with largest population in Idaho is:
            id   city county  state  population      lat       lng stateid
99  1840027142  Boise    Ada  Idaho      448305  43.6005 -116.2308      ID


We are processing State: New Jersey
There are 655 cities in New Jersey.
The city with largest population in New Jersey is:
             id     city  county       state  population      lat      lng  \
114  1840001383  Trenton  Mercer  New Jersey      375343  40.2237 -74.7641

    stateid
114      NJ


We are processing State: Hawaii
There are 158 cities in Hawaii.
The city with largest population in Hawaii is:
             id      city    county   state  population      lat      lng  \
122  1840013305  Honolulu  Honolulu  Hawaii      345482  21.3294 -157.846

    stateid
122      HI


We are processing State: Mississippi
There are 426 cities in Mississippi.
The city with largest population in Mississippi is:
             id     city county        state  population      lat      lng  \
129  1840014895  Jackson  Hinds  Mississippi      333212  32.3157 -90.2125

    stateid
129      MS


We are processing State: Alaska
There are 355 cities in Alaska.
The city with largest population in Alaska is:
             id       city     county   state  population      lat       lng  \
153  1840023385  Anchorage  Anchorage  Alaska      288976  61.1508 -149.1091

    stateid
153      AK


We are processing State: New Hampshire
There are 41 cities in New Hampshire.
The city with largest population in New Hampshire is:
             id    city        county          state  population      lat  \
186  1840002984  Nashua  Hillsborough  New Hampshire      240705  42.7491

        lng stateid
186 -71.491      NH


We are processing State: North Dakota
There are 401 cities in North Dakota.
The city with largest population in North Dakota is:
             id   city county         state  population      lat      lng  \
191  1840000177  Fargo   Cass  North Dakota      231541  46.8651 -96.8292

    stateid
191      ND


We are processing State: Maine
There are 66 cities in Maine.
The city with largest population in Maine is:
             id      city      county  state  population      lat      lng  \
214  1840000327  Portland  Cumberland  Maine      210907  43.6773 -70.2715

    stateid
214      ME


We are processing State: South Dakota
There are 482 cities in South Dakota.
The city with largest population in South Dakota is:
             id         city     county         state  population      lat  \
218  1840002648  Sioux Falls  Minnehaha  South Dakota      207648  43.5396

         lng stateid
218 -96.7311      SD


We are processing State: West Virginia
There are 439 cities in West Virginia.
The city with largest population in West Virginia is:
             id        city  county          state  population      lat  \
238  1840006211  Huntington  Cabell  West Virginia      192569  38.4109

         lng stateid
238 -82.4345      WV


We are processing State: Delaware
There are 79 cities in Delaware.
The city with largest population in Delaware is:
             id   city county     state  population     lat      lng stateid
347  1840005810  Dover   Kent  Delaware      131461  39.161 -75.5202      DE


We are processing State: Montana
There are 495 cities in Montana.
The city with largest population in Montana is:
             id      city       county    state  population      lat  \
354  1840018496  Billings  Yellowstone  Montana      129267  45.7891

          lng stateid
354 -108.5526      MT


We are processing State: Vermont
There are 107 cities in Vermont.
The city with largest population in Vermont is:
             id        city      county    state  population      lat  \
370  1840002310  Burlington  Chittenden  Vermont      122833  44.4876

         lng stateid
370 -73.2316      VT


We are processing State: Wyoming
There are 204 cities in Wyoming.
The city with largest population in Wyoming is:
             id      city   county    state  population     lat       lng  \
595  1840018713  Cheyenne  Laramie  Wyoming       79986  41.135 -104.7902

    stateid
595      WY