In [ ]:
%cd "/content/drive/MyDrive/Colab Notebooks/0ANLY2500SP26/LC/L22Pandas"

/content/drive/MyDrive/Colab Notebooks/0ANLY2500SP26/LC/L22Pandas

In [ ]:
%ls

L22.ipynb  uscity.csv

In [ ]:
import pandas as pd

In [ ]:
mdf=pd.read_csv("uscity.csv")
mdf

,id,city,county,state,population,lat,lng,stateid
0,1840034016,New York,Queens,New York,19268388,40.6943,-73.9249,NY
1,1840020491,Los Angeles,Los Angeles,California,11984083,34.1141,-118.4068,CA
2,1840000494,Chicago,Cook,Illinois,8609571,41.8375,-87.6866,IL
3,1840015149,Miami,Miami-Dade,Florida,6391670,25.7840,-80.2101,FL
4,1840020925,Houston,Harris,Texas,6227666,29.7860,-95.3885,TX
...,...,...,...,...,...,...,...,...
31252,1840025878,Santa Cruz,Pinal,Arizona,0,33.2327,-112.1594,AZ
31253,1840153017,Frankstown,Blair,Pennsylvania,0,40.4444,-78.3558,PA
31254,1840153026,Ski Gap,Blair,Pennsylvania,0,40.3160,-78.5174,PA
31255,1840153079,Sherman,Western Connecticut,Connecticut,0,41.5746,-73.4957,CT
31256,1840153147,Twin Lakes,Mono,California,0,38.1695,-119.3422,CA

In [ ]:
# group by
r=mdf.groupby(by=["state"]) # inside r, there are many groups. Each group is a dataframe (table)

In [ ]:
r.groups.keys()

dict_keys(['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'District of Columbia', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Puerto Rico', 'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming'])

In [ ]:
mdf["state"].unique()
# We get the unique state names. Two ways to do this.

array(['New York', 'California', 'Illinois', 'Florida', 'Texas',
       'Pennsylvania', 'Georgia', 'District of Columbia', 'Massachusetts',
       'Arizona', 'Michigan', 'Washington', 'Minnesota', 'Colorado',
       'Nevada', 'Maryland', 'Missouri', 'Oregon', 'Puerto Rico',
       'Indiana', 'Ohio', 'North Carolina', 'Virginia', 'Rhode Island',
       'Wisconsin', 'Tennessee', 'Utah', 'Oklahoma', 'Connecticut',
       'Kentucky', 'Louisiana', 'Nebraska', 'Alabama', 'New Mexico',
       'South Carolina', 'Iowa', 'Kansas', 'Arkansas', 'Idaho',
       'New Jersey', 'Hawaii', 'Mississippi', 'Alaska', 'New Hampshire',
       'North Dakota', 'Maine', 'South Dakota', 'West Virginia',
       'Delaware', 'Montana', 'Vermont', 'Wyoming'], dtype=object)

In [ ]:
# get one group (dataframe)
c=mdf["state"]=="Utah"
mdf[c]

,id,city,county,state,population,lat,lng,stateid
45,1840021383,Salt Lake City,Salt Lake,Utah,1183003,40.7776,-111.9311,UT
72,1840020174,Provo,Utah,Utah,641732,40.2457,-111.6457,UT
73,1840020135,Ogden,Weber,Utah,630643,41.2279,-111.9682,UT
307,1840021559,St. George,Washington,Utah,148405,37.0758,-113.5752,UT
326,1840021389,West Valley City,Salt Lake,Utah,138437,40.6886,-112.0123,UT
...,...,...,...,...,...,...,...,...
31020,1840024260,Bonanza,Uintah,Utah,0,40.0304,-109.1884,UT
31049,1840022393,Ophir,Tooele,Utah,0,40.3716,-112.2507,UT
31083,1840033695,Cedar Highlands,Iron,Utah,0,37.6295,-113.0667,UT
31225,1840024467,Thompson Springs,Grand,Utah,0,38.9636,-109.7037,UT
31233,1840024370,Clear Creek,Carbon,Utah,0,39.6433,-111.1548,UT

In [ ]:
# get one group
r.get_group("Utah") # is a table (dataframe)

/tmp/ipykernel_361/3443269713.py:2: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  r.get_group("Utah") # is a table (dataframe)

,id,city,county,state,population,lat,lng,stateid
45,1840021383,Salt Lake City,Salt Lake,Utah,1183003,40.7776,-111.9311,UT
72,1840020174,Provo,Utah,Utah,641732,40.2457,-111.6457,UT
73,1840020135,Ogden,Weber,Utah,630643,41.2279,-111.9682,UT
307,1840021559,St. George,Washington,Utah,148405,37.0758,-113.5752,UT
326,1840021389,West Valley City,Salt Lake,Utah,138437,40.6886,-112.0123,UT
...,...,...,...,...,...,...,...,...
31020,1840024260,Bonanza,Uintah,Utah,0,40.0304,-109.1884,UT
31049,1840022393,Ophir,Tooele,Utah,0,40.3716,-112.2507,UT
31083,1840033695,Cedar Highlands,Iron,Utah,0,37.6295,-113.0667,UT
31225,1840024467,Thompson Springs,Grand,Utah,0,38.9636,-109.7037,UT
31233,1840024370,Clear Creek,Carbon,Utah,0,39.6433,-111.1548,UT

In [ ]:
%pwd

'/content/drive/MyDrive/Colab Notebooks/0ANLY2500SP26/LC/L22Pandas'

In [ ]:
%ls

L22.ipynb  uscity.csv

In [ ]:
import pandas as pd

In [ ]:
mdf=pd.read_csv("uscity.csv") # . Tom's
mdf # dataframe, table
# . .
# universe.solar system.earth.usa.utah.cedar city.main street.
# mc donald's.cheese burger

,id,city,county,state,population,lat,lng,stateid
0,1840034016,New York,Queens,New York,19268388,40.6943,-73.9249,NY
1,1840020491,Los Angeles,Los Angeles,California,11984083,34.1141,-118.4068,CA
2,1840000494,Chicago,Cook,Illinois,8609571,41.8375,-87.6866,IL
3,1840015149,Miami,Miami-Dade,Florida,6391670,25.7840,-80.2101,FL
4,1840020925,Houston,Harris,Texas,6227666,29.7860,-95.3885,TX
...,...,...,...,...,...,...,...,...
31252,1840025878,Santa Cruz,Pinal,Arizona,0,33.2327,-112.1594,AZ
31253,1840153017,Frankstown,Blair,Pennsylvania,0,40.4444,-78.3558,PA
31254,1840153026,Ski Gap,Blair,Pennsylvania,0,40.3160,-78.5174,PA
31255,1840153079,Sherman,Western Connecticut,Connecticut,0,41.5746,-73.4957,CT
31256,1840153147,Twin Lakes,Mono,California,0,38.1695,-119.3422,CA

In [ ]:
# groupby() belongs to dataframe (table)
# dataframe: table
# df.groupby()
# groupby() results in multiple tables
# divide a single table into small tables
# groupby(by=[])

In [ ]:
mdf.columns

Index(['id', 'city', 'county', 'state', 'population', 'lat', 'lng', 'stateid'], dtype='object')

In [ ]:
s=mdf["stateid"] #series
s

0        NY
1        CA
2        IL
3        FL
4        TX
         ..
31252    AZ
31253    PA
31254    PA
31255    CT
31256    CA
Name: stateid, Length: 31257, dtype: object

In [ ]:
s.value_counts()

stateid
PA    1886
TX    1836
CA    1598
IL    1456
OH    1253
MO    1081
IA    1024
IN     974
NY     970
FL     945
MN     904
OK     839
WI     792
NC     771
MI     740
KS     738
VA     680
GA     670
NJ     655
WA     633
AR     621
NE     593
AL     592
KY     552
MD     532
NM     520
TN     501
MT     495
LA     489
SD     482
CO     477
SC     473
AZ     461
WV     439
MS     426
OR     425
ND     401
AK     355
UT     332
PR     281
ID     236
WY     204
CT     185
HI     158
NV     132
MA     125
VT     107
DE      79
ME      66
NH      41
RI      31
DC       1
Name: count, dtype: int64

In [ ]:
ss=s.unique()
n=len(ss)
print(ss)
print(n)

['NY' 'CA' 'IL' 'FL' 'TX' 'PA' 'GA' 'DC' 'MA' 'AZ' 'MI' 'WA' 'MN' 'CO'
 'NV' 'MD' 'MO' 'OR' 'PR' 'IN' 'OH' 'NC' 'VA' 'RI' 'WI' 'TN' 'UT' 'OK'
 'CT' 'KY' 'LA' 'NE' 'AL' 'NM' 'SC' 'IA' 'KS' 'AR' 'ID' 'NJ' 'HI' 'MS'
 'AK' 'NH' 'ND' 'ME' 'SD' 'WV' 'DE' 'MT' 'VT' 'WY']
52

In [ ]:
r=mdf.groupby(by=["stateid"])
#

In [ ]:
r.get_group("UT") #dataframe or table

/tmp/ipykernel_361/4102550747.py:1: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  r.get_group("UT") #dataframe or table

,id,city,county,state,population,lat,lng,stateid
45,1840021383,Salt Lake City,Salt Lake,Utah,1183003,40.7776,-111.9311,UT
72,1840020174,Provo,Utah,Utah,641732,40.2457,-111.6457,UT
73,1840020135,Ogden,Weber,Utah,630643,41.2279,-111.9682,UT
307,1840021559,St. George,Washington,Utah,148405,37.0758,-113.5752,UT
326,1840021389,West Valley City,Salt Lake,Utah,138437,40.6886,-112.0123,UT
...,...,...,...,...,...,...,...,...
31020,1840024260,Bonanza,Uintah,Utah,0,40.0304,-109.1884,UT
31049,1840022393,Ophir,Tooele,Utah,0,40.3716,-112.2507,UT
31083,1840033695,Cedar Highlands,Iron,Utah,0,37.6295,-113.0667,UT
31225,1840024467,Thompson Springs,Grand,Utah,0,38.9636,-109.7037,UT
31233,1840024370,Clear Creek,Carbon,Utah,0,39.6433,-111.1548,UT

In [ ]:
#
c=r.groups.keys()
nn=len(c)
print(c)
print(nn)

dict_keys(['AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IA', 'ID', 'IL', 'IN', 'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH', 'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'PR', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA', 'VT', 'WA', 'WI', 'WV', 'WY'])
52

In [ ]:
r=mdf.groupby(by=["stateid"])
#ss=["TX","FL","UT"]
ss=r.groups.keys()
## ss=mdf["stateid"].unique()
for sid in ss:# sid="TX" sid="FL" sid="UT"
  print(sid)
  sdf=r.get_group(sid)
  sdf.to_csv(f"{sid}.csv")
  print(sdf.head(3))
  s=sdf['population']
  tp=s.sum()
  print(tp)

AK
              id       city                county   state  population  \
153   1840023385  Anchorage             Anchorage  Alaska      288976
721   1840023463  Fairbanks  Fairbanks North Star  Alaska       68976
1473  1840023306     Juneau                Juneau  Alaska       31794

          lat       lng stateid
153   61.1508 -149.1091      AK
721   64.8353 -147.6533      AK
1473  58.4546 -134.1739      AK
755969
AL
             id        city     county    state  population      lat      lng  \
60   1840006507  Birmingham  Jefferson  Alabama      773997  33.5279 -86.7971
116  1840005061  Huntsville    Madison  Alabama      368074  34.6981 -86.6412
137  1840006009      Mobile     Mobile  Alabama      316714  30.6782 -88.1162

    stateid
60       AL
116      AL
137      AL
4499400
AR
             id          city      county     state  population      lat  \
94   1840015509   Little Rock     Pulaski  Arkansas      466334  34.7256
108  1840013368  Fayetteville  Washington  Arkansas      408133  36.0714
368  1840013456    Fort Smith   Sebastian  Arkansas      124220  35.3495

         lng stateid
94  -92.3577      AR
108 -94.1661      AR
368 -94.3695      AR
2755925
AZ
            id     city    county    state  population      lat       lng  \
10  1840020568  Phoenix  Maricopa  Arizona     4121103  33.5722 -112.0892
56  1840022101   Tucson      Pima  Arizona      890860  32.1541 -110.8787
85  1840020566     Mesa  Maricopa  Arizona      511764  33.4015 -111.7178

   stateid
10      AZ
56      AZ
85      AZ
9827017
CA
            id           city         county       state  population      lat  \
1   1840020491    Los Angeles    Los Angeles  California    11984083  34.1141
13  1840021543  San Francisco  San Francisco  California     3417736  37.7558
14  1840021990      San Diego      San Diego  California     3064435  32.8313

         lng stateid
1  -118.4068      CA
13 -122.4449      CA
14 -117.1222      CA
57682607
CO
             id              city    county     state  population      lat  \
18   1840018789            Denver    Denver  Colorado     2714768  39.7620
71   1840018825  Colorado Springs   El Paso  Colorado      643336  38.8674
113  1840018794            Aurora  Arapahoe  Colorado      394432  39.7083

          lng stateid
18  -104.8758      CO
71  -104.7605      CO
113 -104.7237      CO
7607104
CT
            id        city                     county        state  \
50  1840004773    Hartford                    Capitol  Connecticut
53  1840004836  Bridgeport         Greater Bridgeport  Connecticut
79  1840004850   New Haven  South Central Connecticut  Connecticut

    population      lat      lng stateid
50      990793  41.7661 -72.6834      CT
53      945974  41.1918 -73.1954      CT
79      567250  41.3113 -72.9246      CT
4268699
DC
           id        city                county                 state  \
8  1840006060  Washington  District of Columbia  District of Columbia

   population      lat      lng stateid
8     5230370  38.9047 -77.0163      DC
5230370
DE
              id        city      county     state  population      lat  \
347   1840005810       Dover        Kent  Delaware      131461  39.1610
688   1840005579  Wilmington  New Castle  Delaware       71727  39.7415
1530  1840005578      Newark  New Castle  Delaware       30330  39.6776

          lng stateid
347  -75.5202      DE
688  -75.5416      DE
1530 -75.7576      DE
531279
FL
            id     city        county    state  population      lat      lng  \
3   1840015149    Miami    Miami-Dade  Florida     6391670  25.7840 -80.2101
15  1840015982    Tampa  Hillsborough  Florida     2957531  27.9945 -82.4447
27  1840015099  Orlando        Orange  Florida     1948155  28.4773 -81.3370

   stateid
3       FL
15      FL
27      FL
31177997
GA
             id      city    county    state  population      lat      lng  \
7    1840013660   Atlanta    Fulton  Georgia     5298788  33.7628 -84.4220
102  1840029462   Augusta  Richmond  Georgia      439238  33.3645 -82.0708
133  1840015830  Savannah   Chatham  Georgia      324227  32.0286 -81.1821

    stateid
7        GA
102      GA
133      GA
11063102
HI
             id           city    county   state  population      lat  \
122  1840013305       Honolulu  Honolulu  Hawaii      345482  21.3294
353  1840023244         Kailua  Honolulu  Hawaii      129469  21.3920
937  1840039181  East Honolulu  Honolulu  Hawaii       51360  21.2975

          lng stateid
122 -157.8460      HI
353 -157.7396      HI
937 -157.7211      HI
1451905
IA

/tmp/ipykernel_361/1731041935.py:7: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  sdf=r.get_group(sid)
/tmp/ipykernel_361/1731041935.py:7: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  sdf=r.get_group(sid)
/tmp/ipykernel_361/1731041935.py:7: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  sdf=r.get_group(sid)
/tmp/ipykernel_361/1731041935.py:7: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  sdf=r.get_group(sid)
/tmp/ipykernel_361/1731041935.py:7: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  sdf=r.get_group(sid)
/tmp/ipykernel_361/1731041935.py:7: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  sdf=r.get_group(sid)
/tmp/ipykernel_361/1731041935.py:7: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  sdf=r.get_group(sid)
/tmp/ipykernel_361/1731041935.py:7: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  sdf=r.get_group(sid)
/tmp/ipykernel_361/1731041935.py:7: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  sdf=r.get_group(sid)
/tmp/ipykernel_361/1731041935.py:7: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  sdf=r.get_group(sid)
/tmp/ipykernel_361/1731041935.py:7: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  sdf=r.get_group(sid)
/tmp/ipykernel_361/1731041935.py:7: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  sdf=r.get_group(sid)
/tmp/ipykernel_361/1731041935.py:7: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  sdf=r.get_group(sid)

             id          city county state  population      lat      lng  \
78   1840007069    Des Moines   Polk  Iowa      570091  41.5725 -93.6105
158  1840007081     Davenport  Scott  Iowa      281044  41.5565 -90.6053
232  1840000471  Cedar Rapids   Linn  Iowa      195323  41.9662 -91.6783

    stateid
78       IA
158      IA
232      IA
3367608
ID
             id           city    county  state  population      lat  \
99   1840027142          Boise       Ada  Idaho      448305  43.6005
226  1840020041          Nampa    Canyon  Idaho      201956  43.5844
346  1840018402  Coeur d'Alene  Kootenai  Idaho      131592  47.7040

          lng stateid
99  -116.2308      ID
226 -116.5638      ID
346 -116.7936      ID
1850144
IL
             id              city     county     state  population      lat  \
2    1840000494           Chicago       Cook  Illinois     8609571  41.8375
166  1840009132          Rockford  Winnebago  Illinois      271411  42.2596
169  1840011171  Round Lake Beach       Lake  Illinois      264501  42.3791

         lng stateid
2   -87.6866      IL
166 -89.0640      IL
169 -88.0811      IL
17933757
IN
             id          city      county    state  population      lat  \
31   1840030084  Indianapolis      Marion  Indiana     1767321  39.7771
126  1840008261    Fort Wayne       Allen  Indiana      339694  41.0888
161  1840009241    South Bend  St. Joseph  Indiana      279977  41.6767

         lng stateid
31  -86.1458      IN
126 -85.1436      IN
161 -86.2696      IN
6400695
KS
             id           city     county   state  population      lat  \
84   1840001686        Wichita   Sedgwick  Kansas      519036  37.6895
228  1840003834  Overland Park    Johnson  Kansas      200306  38.8870
289  1840001626    Kansas City  Wyandotte  Kansas      155135  39.1235

         lng stateid
84  -97.3443      KS
228 -94.6870      KS
289 -94.7443      KS
2628149
KY
             id           city     county     state  population      lat  \
51   1840030815     Louisville  Jefferson  Kentucky      988018  38.1663
134  1840015211      Lexington    Fayette  Kentucky      323725  38.0423
439  1840013265  Bowling Green     Warren  Kentucky      106928  36.9716

         lng stateid
51  -85.6485      KY
134 -84.4587      KY
439 -86.4378      KY
3153126
LA
             id         city            county      state  population  \
55   1840001839  New Orleans           Orleans  Louisiana      928503
68   1840013941  Baton Rouge  East Baton Rouge  Louisiana      654357
164  1840015768   Shreveport             Caddo  Louisiana      276074

         lat      lng stateid
55   30.0687 -89.9288      LA
68   30.4420 -91.1311      LA
164  32.4653 -93.7955      LA
4689761
MA
             id         city     county          state  population      lat  \
9    1840000455       Boston    Suffolk  Massachusetts     4453352  42.3188
87   1840000434    Worcester  Worcester  Massachusetts      496386  42.2705
103  1840000466  Springfield    Hampden  Massachusetts      439199  42.1155

         lng stateid
9   -71.0852      MA
87  -71.8079      MA
103 -72.5395      MA
7991669
MD
             id        city      county     state  population      lat  \
22   1840001592   Baltimore   Baltimore  Maryland     2201673  39.3051
221  1840005613  Hagerstown  Washington  Maryland      204653  39.6401
235  1840005710   Frederick   Frederick  Maryland      195161  39.4337

         lng stateid
22  -76.6144      MD
221 -77.7217      MD
235 -77.4141      MD
7197301
ME
              id      city        county  state  population      lat      lng  \
214   1840000327  Portland    Cumberland  Maine      210907  43.6773 -70.2715
1218  1840000320  Lewiston  Androscoggin  Maine       38324  44.0915 -70.1681
1467  1840000238    Bangor     Penobscot  Maine       31938  44.8323 -68.7906

     stateid
214       ME
1218      ME
1467      ME
594488
MI
             id          city  county     state  population      lat      lng  \
11   1840003971       Detroit   Wayne  Michigan     3773725  42.3834 -83.1024
75   1840002928  Grand Rapids    Kent  Michigan      622168  42.9619 -85.6562
131  1840003102       Lansing  Ingham  Michigan      328527  42.7142 -84.5601

    stateid
11       MI
75       MI
131      MI
10467252
MN

/tmp/ipykernel_361/1731041935.py:7: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  sdf=r.get_group(sid)
/tmp/ipykernel_361/1731041935.py:7: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  sdf=r.get_group(sid)
/tmp/ipykernel_361/1731041935.py:7: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  sdf=r.get_group(sid)
/tmp/ipykernel_361/1731041935.py:7: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  sdf=r.get_group(sid)
/tmp/ipykernel_361/1731041935.py:7: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  sdf=r.get_group(sid)
/tmp/ipykernel_361/1731041935.py:7: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  sdf=r.get_group(sid)
/tmp/ipykernel_361/1731041935.py:7: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  sdf=r.get_group(sid)
/tmp/ipykernel_361/1731041935.py:7: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  sdf=r.get_group(sid)
/tmp/ipykernel_361/1731041935.py:7: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  sdf=r.get_group(sid)
/tmp/ipykernel_361/1731041935.py:7: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  sdf=r.get_group(sid)
/tmp/ipykernel_361/1731041935.py:7: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  sdf=r.get_group(sid)

             id         city    county      state  population      lat  \
16   1840007830  Minneapolis  Hennepin  Minnesota     2937866  44.9635
142  1840008940     St. Paul    Ramsey  Minnesota      307284  44.9478
369  1840008987    Rochester   Olmsted  Minnesota      122867  44.0154

         lng stateid
16  -93.2678      MN
142 -93.1039      MN
369 -92.4780      MN
7388296
MO
             id         city     county     state  population      lat  \
23   1840001651    St. Louis  St. Louis  Missouri     2129918  38.6359
34   1840008535  Kansas City    Jackson  Missouri     1714910  39.1238
144  1840009904  Springfield     Greene  Missouri      300073  37.1943

         lng stateid
23  -90.2451      MO
34  -94.5541      MO
144 -93.2916      MO
7643384
MS
             id         city    county        state  population      lat  \
129  1840014895      Jackson     Hinds  Mississippi      333212  32.3157
182  1840013947     Gulfport  Harrison  Mississippi      244766  30.4274
599  1840013878  Hattiesburg   Forrest  Mississippi       79749  31.3074

         lng stateid
129 -90.2125      MS
182 -89.0704      MS
599 -89.3170      MS
2043876
MT
             id         city       county    state  population      lat  \
354  1840018496     Billings  Yellowstone  Montana      129267  45.7891
518  1840019840     Missoula     Missoula  Montana       90522  46.8751
727  1840019839  Great Falls      Cascade  Montana       68580  47.5022

          lng stateid
354 -108.5526      MT
518 -114.0214      MT
727 -111.2996      MT
825974
NC
             id           city       county           state  population  \
38   1840014557      Charlotte  Mecklenburg  North Carolina     1488249
46   1840014497        Raleigh         Wake  North Carolina     1179118
100  1840015324  Winston-Salem      Forsyth  North Carolina      443598

         lat      lng stateid
38   35.2083 -80.8303      NC
46   35.8324 -78.6429      NC
100  36.1029 -80.2610      NC
9506178
ND
             id         city       county         state  population      lat  \
191  1840000177        Fargo         Cass  North Dakota      231541  46.8651
469  1840001926     Bismarck     Burleigh  North Dakota      100537  46.8143
731  1840000101  Grand Forks  Grand Forks  North Dakota       68373  47.9214

          lng stateid
191  -96.8292      ND
469 -100.7694      ND
731  -97.0884      ND
756983
NE
             id      city     county     state  population      lat      lng  \
58   1840009315     Omaha    Douglas  Nebraska      836740  41.2627 -96.0529
146  1840009357   Lincoln  Lancaster  Nebraska      298056  40.8099 -96.6784
777  1840007142  Bellevue      Sarpy  Nebraska       64510  41.1485 -95.9390

    stateid
58       NE
146      NE
777      NE
1942696
NH
             id        city        county          state  population      lat  \
186  1840002984      Nashua  Hillsborough  New Hampshire      240705  42.7491
270  1840002983  Manchester  Hillsborough  New Hampshire      167888  42.9848
453  1840002932  Portsmouth    Rockingham  New Hampshire      104019  43.0580

         lng stateid
186 -71.4910      NH
270 -71.4447      NH
453 -70.7826      NH
803240
NJ
             id         city  county       state  population      lat  \
114  1840001383      Trenton  Mercer  New Jersey      375343  40.2237
141  1840002791       Newark   Essex  New Jersey      310178  40.7245
149  1840003600  Jersey City  Hudson  New Jersey      294078  40.7184

         lng stateid
114 -74.7641      NJ
141 -74.1725      NJ
149 -74.0686      NJ
6024651
NM
             id         city      county       state  population      lat  \
61   1840019176  Albuquerque  Bernalillo  New Mexico      765360  35.1054
322  1840020683   Las Cruces    Doña Ana  New Mexico      139530  32.3265
427  1840020387   Rio Rancho    Sandoval  New Mexico      108515  35.2873

          lng stateid
61  -106.6465      NM
322 -106.7893      NM
427 -106.6982      NM
2060586
NV
             id       city  county   state  population      lat       lng  \
21   1840020364  Las Vegas   Clark  Nevada     2299189  36.2333 -115.2654
93   1840020121       Reno  Washoe  Nevada      466706  39.5497 -119.8483
130  1840020361  Henderson   Clark  Nevada      332141  36.0133 -115.0381

    stateid
21       NV
93       NV
130      NV
4882687
NY
            id      city  county     state  population      lat      lng  \
0   1840034016  New York  Queens  New York    19268388  40.6943 -73.9249
17  1840034030  Brooklyn   Kings  New York     2736074  40.6501 -73.9496
19  1840034002    Queens  Queens  New York     2405464  40.7498 -73.7976

   stateid
0       NY
17      NY
19      NY
37151510
OH

/tmp/ipykernel_361/1731041935.py:7: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  sdf=r.get_group(sid)
/tmp/ipykernel_361/1731041935.py:7: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  sdf=r.get_group(sid)
/tmp/ipykernel_361/1731041935.py:7: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  sdf=r.get_group(sid)
/tmp/ipykernel_361/1731041935.py:7: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  sdf=r.get_group(sid)
/tmp/ipykernel_361/1731041935.py:7: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  sdf=r.get_group(sid)
/tmp/ipykernel_361/1731041935.py:7: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  sdf=r.get_group(sid)
/tmp/ipykernel_361/1731041935.py:7: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  sdf=r.get_group(sid)
/tmp/ipykernel_361/1731041935.py:7: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  sdf=r.get_group(sid)
/tmp/ipykernel_361/1731041935.py:7: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  sdf=r.get_group(sid)
/tmp/ipykernel_361/1731041935.py:7: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  sdf=r.get_group(sid)
/tmp/ipykernel_361/1731041935.py:7: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  sdf=r.get_group(sid)
/tmp/ipykernel_361/1731041935.py:7: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  sdf=r.get_group(sid)

            id        city    county state  population      lat      lng  \
33  1840003814  Cincinnati  Hamilton  Ohio     1726642  39.1413 -84.5060
35  1840000596   Cleveland  Cuyahoga  Ohio     1695555  41.4764 -81.6805
37  1840003760    Columbus  Franklin  Ohio     1635039  39.9862 -82.9855

   stateid
33      OH
35      OH
37      OH
13688462
OK
             id           city     county     state  population      lat  \
49   1840020428  Oklahoma City   Oklahoma  Oklahoma     1017828  35.4676
62   1840021672          Tulsa      Tulsa  Oklahoma      747529  36.1283
352  1840020451         Norman  Cleveland  Oklahoma      129672  35.2335

         lng stateid
49  -97.5136      OK
62  -95.9042      OK
352 -97.3471      OK
3864008
OR
             id      city     county   state  population      lat       lng  \
24   1840019941  Portland  Multnomah  Oregon     2115140  45.5371 -122.6500
165  1840020007    Eugene       Lane  Oregon      272404  44.0564 -123.1174
168  1840021224     Salem     Marion  Oregon      268719  44.9233 -123.0244

    stateid
24       OR
165      OR
168      OR
5238934
PA
            id          city        county         state  population      lat  \
6   1840000673  Philadelphia  Philadelphia  Pennsylvania     5782653  40.0077
32  1840001254    Pittsburgh     Allegheny  Pennsylvania     1729616  40.4397
70  1840001044     Allentown        Lehigh  Pennsylvania      644758  40.5961

        lng stateid
6  -75.1339      PA
32 -79.9763      PA
70 -75.4756      PA
15003787
PR
             id       city     county        state  population      lat  \
30   1630035577   San Juan   San Juan  Puerto Rico     1813477  18.3985
196  1630035605  Aguadilla  Aguadilla  Puerto Rico      225238  18.4382
272  1630035622    Bayamón    Bayamón  Puerto Rico      166923  18.3794

         lng stateid
30  -66.0610      PR
196 -67.1537      PR
272 -66.1635      PR
3867284
RI
             id        city      county         state  population      lat  \
42   1840003289  Providence  Providence  Rhode Island     1292041  41.8230
561  1840003287    Cranston  Providence  Rhode Island       83250  41.7658
562  1840003344     Warwick        Kent  Rhode Island       83175  41.7062

         lng stateid
42  -71.4187      RI
561 -71.4858      RI
562 -71.4334      RI
1744858
SC
             id        city      county           state  population      lat  \
63   1840015163  Charleston  Charleston  South Carolina      734681  32.8168
76   1840014730    Columbia    Richland  South Carolina      610536  34.0378
110  1840013501  Greenville  Greenville  South Carolina      402612  34.8354

         lng stateid
63  -79.9687      SC
76  -80.9036      SC
110 -82.3646      SC
4976512
SD
              id         city      county         state  population      lat  \
218   1840002648  Sioux Falls   Minnehaha  South Dakota      207648  43.5396
502   1840002180   Rapid City  Pennington  South Dakota       92897  44.0716
1632  1840002032     Aberdeen       Brown  South Dakota       28189  45.4649

           lng stateid
218   -96.7311      SD
502  -103.2204      SD
1632  -98.4686      SD
738164
TN
            id       city    county      state  population      lat      lng  \
44  1840036155  Nashville  Davidson  Tennessee     1201962  36.1715 -86.7842
48  1840015457    Memphis    Shelby  Tennessee     1037125  35.1087 -89.9663
74  1840014486  Knoxville      Knox  Tennessee      627090  35.9692 -83.9496

   stateid
44      TN
48      TN
74      TN
6447959
TX
            id         city  county  state  population      lat      lng  \
4   1840020925      Houston  Harris  Texas     6227666  29.7860 -95.3885
5   1840019440       Dallas  Dallas  Texas     5968322  32.7935 -96.7667
25  1840022220  San Antonio   Bexar  Texas     2096390  29.4632 -98.5238

   stateid
4       TX
5       TX
25      TX
35374017
UT
            id            city     county state  population      lat  \
45  1840021383  Salt Lake City  Salt Lake  Utah     1183003  40.7776
72  1840020174           Provo       Utah  Utah      641732  40.2457
73  1840020135           Ogden      Weber  Utah      630643  41.2279

         lng stateid
45 -111.9311      UT
72 -111.6457      UT
73 -111.9682      UT
5419952
VA
             id            city          county     state  population  \
40   1840003871  Virginia Beach  Virginia Beach  Virginia     1441893
47   1840001698        Richmond        Richmond  Virginia     1098457
180  1840003874      Chesapeake      Chesapeake  Virginia      252583

         lat      lng stateid
40   36.7335 -76.0435      VA
47   37.5295 -77.4756      VA
180  36.6778 -76.3023      VA
8404245
VT

/tmp/ipykernel_361/1731041935.py:7: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  sdf=r.get_group(sid)
/tmp/ipykernel_361/1731041935.py:7: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  sdf=r.get_group(sid)
/tmp/ipykernel_361/1731041935.py:7: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  sdf=r.get_group(sid)
/tmp/ipykernel_361/1731041935.py:7: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  sdf=r.get_group(sid)
/tmp/ipykernel_361/1731041935.py:7: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  sdf=r.get_group(sid)
/tmp/ipykernel_361/1731041935.py:7: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  sdf=r.get_group(sid)
/tmp/ipykernel_361/1731041935.py:7: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  sdf=r.get_group(sid)
/tmp/ipykernel_361/1731041935.py:7: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  sdf=r.get_group(sid)
/tmp/ipykernel_361/1731041935.py:7: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  sdf=r.get_group(sid)
/tmp/ipykernel_361/1731041935.py:7: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  sdf=r.get_group(sid)
/tmp/ipykernel_361/1731041935.py:7: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  sdf=r.get_group(sid)
/tmp/ipykernel_361/1731041935.py:7: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  sdf=r.get_group(sid)

              id              city      county    state  population      lat  \
370   1840002310        Burlington  Chittenden  Vermont      122833  44.4876
2207  1840002311  South Burlington  Chittenden  Vermont       20756  44.4622
2847  1840002632           Rutland     Rutland  Vermont       15712  43.6092

          lng stateid
370  -73.2316      VT
2207 -73.2202      VT
2847 -72.9783      VT
258291
WA
             id       city   county       state  population      lat  \
12   1840021117    Seattle     King  Washington     3642006  47.6211
96   1840021093    Spokane  Spokane  Washington      462286  47.6671
173  1840018481  Kennewick   Benton  Washington      259487  46.1978

          lng stateid
12  -122.3244      WA
96  -117.4330      WA
173 -119.1732      WA
10432766
WI
             id       city     county      state  population      lat  \
43   1840003046  Milwaukee  Milwaukee  Wisconsin     1291752  43.0642
91   1840002915    Madison       Dane  Wisconsin      470689  43.0822
192  1840002400   Appleton  Outagamie  Wisconsin      230473  44.2780

         lng stateid
43  -87.9675      WI
91  -89.3930      WI
192 -88.3892      WI
5832123
WV
             id        city      county          state  population      lat  \
238  1840006211  Huntington      Cabell  West Virginia      192569  38.4109
329  1840006196  Charleston     Kanawha  West Virginia      137865  38.3484
618  1840005647  Morgantown  Monongalia  West Virginia       77875  39.6383

         lng stateid
238 -82.4345      WV
329 -81.6322      WV
618 -79.9464      WV
1067431
WY
              id      city    county    state  population      lat       lng  \
595   1840018713  Cheyenne   Laramie  Wyoming       79986  41.1350 -104.7902
764   1840038324    Casper   Natrona  Wyoming       65842  42.8420 -106.3208
1400  1840019978  Gillette  Campbell  Wyoming       33431  44.2752 -105.4982

     stateid
595       WY
764       WY
1400      WY
478443

/tmp/ipykernel_361/1731041935.py:7: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  sdf=r.get_group(sid)
/tmp/ipykernel_361/1731041935.py:7: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  sdf=r.get_group(sid)
/tmp/ipykernel_361/1731041935.py:7: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  sdf=r.get_group(sid)
/tmp/ipykernel_361/1731041935.py:7: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  sdf=r.get_group(sid)

In [ ]:
%ls

AK.csv  CT.csv  IA.csv  L22.ipynb  MN.csv  NE.csv  OH.csv  SC.csv      VA.csv
AL.csv  DC.csv  ID.csv  LA.csv     MO.csv  NH.csv  OK.csv  SD.csv      VT.csv
AR.csv  DE.csv  IL.csv  MA.csv     MS.csv  NJ.csv  OR.csv  TN.csv      WA.csv
AZ.csv  FL.csv  IN.csv  MD.csv     MT.csv  NM.csv  PA.csv  TX.csv      WI.csv
CA.csv  GA.csv  KS.csv  ME.csv     NC.csv  NV.csv  PR.csv  uscity.csv  WV.csv
CO.csv  HI.csv  KY.csv  MI.csv     ND.csv  NY.csv  RI.csv  UT.csv      WY.csv