# Problem Statement- MovieLens Case Study  
**Context**

The movie rating system has been around for over 50 years. Over the years, cultural standards and norms have changed, and so have movie ratings. However, even today, the process of rating a film remains a closely guarded industry secret.
   
**Objective**

MovieLens is a company operating in the internet and entertainment domain, featuring an extensive online database that includes information related to films, television series, and online streaming content. This database encompasses details such as cast, production crew, trivia, ratings, and both fan and critical reviews.

As a newly hired Data Scientist at MovieLens, you have been provided with three datasets. Your task is to conduct a thorough analysis of this data and derive meaningful insights that will assist the company in better addressing the needs of its users.

There are two options for this assignment.

### Option 1

For this assignment, you can simply run the provided code for **Option 1** to get started. You do not need to download the data files `movies.csv`, `users.csv`, and `ratings.csv` and upload it to your Google Drive.

If you choose this option, you can skip the steps for:

* Connecting to Google Drive
* Setting the current folder

### Option 2

If you prefer, you may download the data files `movies.csv`, `users.csv`, and `ratings.csv`, upload it to your Google Drive, connect Google Colab to your Google Drive, and set the appropriate current folder.

This option is also acceptable. If you choose this approach, you may need to delete or modify the provided code in for **Option 1**.

## Import necessary packages

In [ ]:
# Import necessary libraries and packages
import pandas as pd
import numpy as np

## Read the datasets

In [ ]:
# Mount your drive
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
# Change current directory
%cd "/content/drive/MyDrive/Colab Notebooks/ANLY2500/HW/path of the new directory"

In [ ]:
 # Verify the current directory
%pwd

## Option 1 Code

In [ ]:
# Load all three datasets
# Run the following code to start if you choose option 1.
import pandas as pd
movies = pd.read_csv("https://juxinglongsuuta.github.io/anly2500/movies.csv")
users = pd.read_csv("https://juxinglongsuuta.github.io/anly2500/ratings.csv")
ratings = pd.read_csv("https://juxinglongsuuta.github.io/anly2500/users.csv")

## Task 1 - Data overview
The initial steps to understand any dataset are to:

1. Observe the First Few Rows: Check the first few rows of the dataset to confirm that it has been loaded properly.
1. Get Information About Dimensions: Determine the number of rows and columns in the dataset.
1. Examine Data Types: Identify the data types of the columns to ensure that the data is stored in the preferred format and that the values of each property are as expected.
1. Check Statistical Summary: Review the statistical summary of the dataset to gain an overview of the numerical columns.

### User dataset

### Task 1.1 (0.5 points)
#### Display the first 5 rows of the dataset.


<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>user id</th>
      <th>age</th>
      <th>gender</th>
      <th>occupation</th>
      <th>zip code</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1</td>
      <td>24</td>
      <td>M</td>
      <td>technician</td>
      <td>85711</td>
    </tr>
    <tr>
      <th>1</th>
      <td>2</td>
      <td>53</td>
      <td>F</td>
      <td>other</td>
      <td>94043</td>
    </tr>
    <tr>
      <th>2</th>
      <td>3</td>
      <td>23</td>
      <td>M</td>
      <td>writer</td>
      <td>32067</td>
    </tr>
    <tr>
      <th>3</th>
      <td>4</td>
      <td>24</td>
      <td>M</td>
      <td>technician</td>
      <td>43537</td>
    </tr>
    <tr>
      <th>4</th>
      <td>5</td>
      <td>33</td>
      <td>F</td>
      <td>other</td>
      <td>15213</td>
    </tr>
  </tbody>
</table>

In [ ]:
# Provide your answer here.

### Task 1.2 (0.5 points)

#### Identify the dimensions of the dataset using the shape attribute.

(943, 5)

In [ ]:
# Provide your answer here.

### Task 1.3 (0.5 points)

#### Let's look at the data types. The info() function will help us understand the data types of each column.
```text
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 943 entries, 0 to 942
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   user id     943 non-null    int64
 1   age         943 non-null    int64
 2   gender      943 non-null    object
 3   occupation  943 non-null    object
 4   zip code    943 non-null    object
dtypes: int64(2), object(3)
memory usage: 37.0+ KB
```

In [ ]:
# Provide your answer here.

### Task 1.4 (0.5 points)

#### Let's take a look at the statistical summary of the dataset. The describe() function will help us find the statistical summary.

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>user id</th>
      <th>age</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>count</th>
      <td>943.000000</td>
      <td>943.000000</td>
    </tr>
    <tr>
      <th>mean</th>
      <td>472.000000</td>
      <td>34.051962</td>
    </tr>
    <tr>
      <th>std</th>
      <td>272.364951</td>
      <td>12.192740</td>
    </tr>
    <tr>
      <th>min</th>
      <td>1.000000</td>
      <td>7.000000</td>
    </tr>
    <tr>
      <th>25%</th>
      <td>236.500000</td>
      <td>25.000000</td>
    </tr>
    <tr>
      <th>50%</th>
      <td>472.000000</td>
      <td>31.000000</td>
    </tr>
    <tr>
      <th>75%</th>
      <td>707.500000</td>
      <td>43.000000</td>
    </tr>
    <tr>
      <th>max</th>
      <td>943.000000</td>
      <td>73.000000</td>
    </tr>
  </tbody>
</table>

In [ ]:
# Provide your answer here.

### Movie dataset

### Task 1.5 (0.5 points)

#### Display the first 5 rows of the dataset.

<div style="overflow-x:auto;">
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>movie id</th>
      <th>movie title</th>
      <th>release date</th>
      <th>Action</th>
      <th>Adventure</th>
      <th>Animation</th>
      <th>Childrens</th>
      <th>Comedy</th>
      <th>Crime</th>
      <th>Documentary</th>
      <th>...</th>
      <th>Fantasy</th>
      <th>Film-Noir</th>
      <th>Horror</th>
      <th>Musical</th>
      <th>Mystery</th>
      <th>Romance</th>
      <th>Sci-Fi</th>
      <th>Thriller</th>
      <th>War</th>
      <th>Western</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1</td>
      <td>Toy Story</td>
      <td>1-Jan-95</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>1</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>1</th>
      <td>2</td>
      <td>GoldenEye</td>
      <td>1-Jan-95</td>
      <td>1</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>2</th>
      <td>3</td>
      <td>Four Rooms</td>
      <td>1-Jan-95</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>3</th>
      <td>4</td>
      <td>Get Shorty</td>
      <td>1-Jan-95</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>4</th>
      <td>5</td>
      <td>Copycat</td>
      <td>1-Jan-95</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
    </tr>
  </tbody>
</table>
<p>5 rows × 21 columns</p>
</div>

In [ ]:
# Provide your answer here.

### Task 1.6 (0.5 points)

#### Identify the dimensions of the dataset using the shape attribute.

(1680, 21)

In [ ]:
# Provide your answer here.

### Task 1.7 (0.5 points)

#### Check the data types using the info() function.

```text
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1680 entries, 0 to 1679
Data columns (total 21 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   movie id      1680 non-null   int64
 1   movie title   1680 non-null   object
 2   release date  1680 non-null   object
 3   Action        1680 non-null   int64
 4   Adventure     1680 non-null   int64
 5   Animation     1680 non-null   int64
 6   Childrens     1680 non-null   int64
 7   Comedy        1680 non-null   int64
 8   Crime         1680 non-null   int64
 9   Documentary   1680 non-null   int64
 10  Drama         1680 non-null   int64
 11  Fantasy       1680 non-null   int64
 12  Film-Noir     1680 non-null   int64
 13  Horror        1680 non-null   int64
 14  Musical       1680 non-null   int64
 15  Mystery       1680 non-null   int64
 16  Romance       1680 non-null   int64
 17  Sci-Fi        1680 non-null   int64
 18  Thriller      1680 non-null   int64
 19  War           1680 non-null   int64
 20  Western       1680 non-null   int64
dtypes: int64(19), object(2)
memory usage: 275.8+ KB
```

In [ ]:
# Provide your answer here.

### Task 1.8 (0.5 points)

#### Obtain the statistical summary of the dataset.

<div style="overflow-x:auto;">
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>movie id</th>
      <th>Action</th>
      <th>Adventure</th>
      <th>Animation</th>
      <th>Childrens</th>
      <th>Comedy</th>
      <th>Crime</th>
      <th>Documentary</th>
      <th>Drama</th>
      <th>Fantasy</th>
      <th>Film-Noir</th>
      <th>Horror</th>
      <th>Musical</th>
      <th>Mystery</th>
      <th>Romance</th>
      <th>Sci-Fi</th>
      <th>Thriller</th>
      <th>War</th>
      <th>Western</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>count</th>
      <td>1680.000000</td>
      <td>1680.000000</td>
      <td>1680.000000</td>
      <td>1680.000000</td>
      <td>1680.000000</td>
      <td>1680.000000</td>
      <td>1680.000000</td>
      <td>1680.000000</td>
      <td>1680.000000</td>
      <td>1680.000000</td>
      <td>1680.000000</td>
      <td>1680.000000</td>
      <td>1680.000000</td>
      <td>1680.000000</td>
      <td>1680.000000</td>
      <td>1680.000000</td>
      <td>1680.000000</td>
      <td>1680.000000</td>
      <td>1680.000000</td>
    </tr>
    <tr>
      <th>mean</th>
      <td>841.525595</td>
      <td>0.149405</td>
      <td>0.080357</td>
      <td>0.025000</td>
      <td>0.072619</td>
      <td>0.300595</td>
      <td>0.064881</td>
      <td>0.029762</td>
      <td>0.431548</td>
      <td>0.013095</td>
      <td>0.014286</td>
      <td>0.054762</td>
      <td>0.033333</td>
      <td>0.036310</td>
      <td>0.147024</td>
      <td>0.060119</td>
      <td>0.149405</td>
      <td>0.042262</td>
      <td>0.016071</td>
    </tr>
    <tr>
      <th>std</th>
      <td>485.609591</td>
      <td>0.356593</td>
      <td>0.271926</td>
      <td>0.156171</td>
      <td>0.259587</td>
      <td>0.458653</td>
      <td>0.246389</td>
      <td>0.169980</td>
      <td>0.495440</td>
      <td>0.113717</td>
      <td>0.118701</td>
      <td>0.227583</td>
      <td>0.179559</td>
      <td>0.187115</td>
      <td>0.354235</td>
      <td>0.237778</td>
      <td>0.356593</td>
      <td>0.201246</td>
      <td>0.125788</td>
    </tr>
    <tr>
      <th>min</th>
      <td>1.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>25%</th>
      <td>421.750000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>50%</th>
      <td>841.500000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>75%</th>
      <td>1261.250000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>1.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>1.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>max</th>
      <td>1682.000000</td>
      <td>1.000000</td>
      <td>1.000000</td>
      <td>1.000000</td>
      <td>1.000000</td>
      <td>1.000000</td>
      <td>1.000000</td>
      <td>1.000000</td>
      <td>1.000000</td>
      <td>1.000000</td>
      <td>1.000000</td>
      <td>1.000000</td>
      <td>1.000000</td>
      <td>1.000000</td>
      <td>1.000000</td>
      <td>1.000000</td>
      <td>1.000000</td>
      <td>1.000000</td>
      <td>1.000000</td>
    </tr>
  </tbody>
</table>
</div>

In [ ]:
# Provide your answer here.

### Rating dataset

### Task 1.9 (0.5 points)

#### Display the first 5 rows of the dataset.

<div>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>user id</th>
      <th>movie id</th>
      <th>rating</th>
      <th>timestamp</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>196</td>
      <td>242</td>
      <td>3</td>
      <td>881250949</td>
    </tr>
    <tr>
      <th>1</th>
      <td>186</td>
      <td>302</td>
      <td>3</td>
      <td>891717742</td>
    </tr>
    <tr>
      <th>2</th>
      <td>22</td>
      <td>377</td>
      <td>1</td>
      <td>878887116</td>
    </tr>
    <tr>
      <th>3</th>
      <td>244</td>
      <td>51</td>
      <td>2</td>
      <td>880606923</td>
    </tr>
    <tr>
      <th>4</th>
      <td>166</td>
      <td>346</td>
      <td>1</td>
      <td>886397596</td>
    </tr>
  </tbody>
</table>
</div>

In [ ]:
# Provide your answer here.

### Task 1.10 (0.5 points)

#### Identify the dimensions of the dataset using the shape attribute.

(100000, 4)

In [ ]:
# Provide your answer here.

### Task 1.11 (0.5 points)

#### Check the data types using the info() function.

```text
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 4 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   user id    100000 non-null  int64
 1   movie id   100000 non-null  int64
 2   rating     100000 non-null  int64
 3   timestamp  100000 non-null  int64
dtypes: int64(4)
memory usage: 3.1 MB
```

In [ ]:
# Provide your answer here.

### Task 1.12 (0.5 points)

#### Obtain the statistical summary of the dataset.

<div style="overflow-x:auto;">
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>user id</th>
      <th>movie id</th>
      <th>rating</th>
      <th>timestamp</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>count</th>
      <td>100000.00000</td>
      <td>100000.000000</td>
      <td>100000.000000</td>
      <td>1.000000e+05</td>
    </tr>
    <tr>
      <th>mean</th>
      <td>462.48475</td>
      <td>425.530130</td>
      <td>3.529860</td>
      <td>8.835289e+08</td>
    </tr>
    <tr>
      <th>std</th>
      <td>266.61442</td>
      <td>330.798356</td>
      <td>1.125674</td>
      <td>5.343856e+06</td>
    </tr>
    <tr>
      <th>min</th>
      <td>1.00000</td>
      <td>1.000000</td>
      <td>1.000000</td>
      <td>8.747247e+08</td>
    </tr>
    <tr>
      <th>25%</th>
      <td>254.00000</td>
      <td>175.000000</td>
      <td>3.000000</td>
      <td>8.794487e+08</td>
    </tr>
    <tr>
      <th>50%</th>
      <td>447.00000</td>
      <td>322.000000</td>
      <td>4.000000</td>
      <td>8.828269e+08</td>
    </tr>
    <tr>
      <th>75%</th>
      <td>682.00000</td>
      <td>631.000000</td>
      <td>4.000000</td>
      <td>8.882600e+08</td>
    </tr>
    <tr>
      <th>max</th>
      <td>943.00000</td>
      <td>1682.000000</td>
      <td>5.000000</td>
      <td>8.932866e+08</td>
    </tr>
  </tbody>
</table>
</div>

In [ ]:
# Provide your answer here.

## Let's extract some meaningful insights from the data by answering a few questions.

## Task 2 - How many movies belong to each genre?

### Task 2.1

#### Get all columns to identify the genres of the movies. Create a variable `column_names` to store these column name values as a list.

#### Retrieve the DataFrame containing only the genre columns.

#### Use the `sum()` function to obtain the number of movies in each genre.


<div style="overflow-x:auto;">
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Genre</th>
      <th>Movies</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>Action</td>
      <td>251</td>
    </tr>
    <tr>
      <th>1</th>
      <td>Adventure</td>
      <td>135</td>
    </tr>
    <tr>
      <th>2</th>
      <td>Animation</td>
      <td>42</td>
    </tr>
    <tr>
      <th>3</th>
      <td>Childrens</td>
      <td>122</td>
    </tr>
    <tr>
      <th>4</th>
      <td>Comedy</td>
      <td>505</td>
    </tr>
    <tr>
      <th>5</th>
      <td>Crime</td>
      <td>109</td>
    </tr>
    <tr>
      <th>6</th>
      <td>Documentary</td>
      <td>50</td>
    </tr>
    <tr>
      <th>7</th>
      <td>Drama</td>
      <td>725</td>
    </tr>
    <tr>
      <th>8</th>
      <td>Fantasy</td>
      <td>22</td>
    </tr>
    <tr>
      <th>9</th>
      <td>Film-Noir</td>
      <td>24</td>
    </tr>
    <tr>
      <th>10</th>
      <td>Horror</td>
      <td>92</td>
    </tr>
    <tr>
      <th>11</th>
      <td>Musical</td>
      <td>56</td>
    </tr>
    <tr>
      <th>12</th>
      <td>Mystery</td>
      <td>61</td>
    </tr>
    <tr>
      <th>13</th>
      <td>Romance</td>
      <td>247</td>
    </tr>
    <tr>
      <th>14</th>
      <td>Sci-Fi</td>
      <td>101</td>
    </tr>
    <tr>
      <th>15</th>
      <td>Thriller</td>
      <td>251</td>
    </tr>
    <tr>
      <th>16</th>
      <td>War</td>
      <td>71</td>
    </tr>
    <tr>
      <th>17</th>
      <td>Western</td>
      <td>27</td>
    </tr>
  </tbody>
</table>
</div>

In [ ]:
movies.columns

In [ ]:
genres_list=['Action', 'Adventure', 'Animation', 'Childrens', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy', 'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']
genres_list

In [ ]:
n_movies_per_genre = movies[genres_list].sum().reset_index(drop=False)
n_movies_per_genre.rename(columns={'index':'Genre',0:"Movies"},inplace=True)
n_movies_per_genre

### Task 2.2 (1 point)

#### Sort the values to arrange the numbers in ascending order.

<div style="overflow-x:auto;">
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Genre</th>
      <th>Movies</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>Fantasy</td>
      <td>22</td>
    </tr>
    <tr>
      <th>1</th>
      <td>Film-Noir</td>
      <td>24</td>
    </tr>
    <tr>
      <th>2</th>
      <td>Western</td>
      <td>27</td>
    </tr>
    <tr>
      <th>3</th>
      <td>Animation</td>
      <td>42</td>
    </tr>
    <tr>
      <th>4</th>
      <td>Documentary</td>
      <td>50</td>
    </tr>
    <tr>
      <th>5</th>
      <td>Musical</td>
      <td>56</td>
    </tr>
    <tr>
      <th>6</th>
      <td>Mystery</td>
      <td>61</td>
    </tr>
    <tr>
      <th>7</th>
      <td>War</td>
      <td>71</td>
    </tr>
    <tr>
      <th>8</th>
      <td>Horror</td>
      <td>92</td>
    </tr>
    <tr>
      <th>9</th>
      <td>Sci-Fi</td>
      <td>101</td>
    </tr>
    <tr>
      <th>10</th>
      <td>Crime</td>
      <td>109</td>
    </tr>
    <tr>
      <th>11</th>
      <td>Childrens</td>
      <td>122</td>
    </tr>
    <tr>
      <th>12</th>
      <td>Adventure</td>
      <td>135</td>
    </tr>
    <tr>
      <th>13</th>
      <td>Romance</td>
      <td>247</td>
    </tr>
    <tr>
      <th>14</th>
      <td>Thriller</td>
      <td>251</td>
    </tr>
    <tr>
      <th>15</th>
      <td>Action</td>
      <td>251</td>
    </tr>
    <tr>
      <th>16</th>
      <td>Comedy</td>
      <td>505</td>
    </tr>
    <tr>
      <th>17</th>
      <td>Drama</td>
      <td>725</td>
    </tr>
  </tbody>
</table>
</div>

In [ ]:
# Provide your answer here.

### Task 2.3 (1 point)

#### Sort the values to arrange the numbers in descending order.

<div style="overflow-x:auto;">
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Genre</th>
      <th>Movies</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>Drama</td>
      <td>725</td>
    </tr>
    <tr>
      <th>1</th>
      <td>Comedy</td>
      <td>505</td>
    </tr>
    <tr>
      <th>2</th>
      <td>Action</td>
      <td>251</td>
    </tr>
    <tr>
      <th>3</th>
      <td>Thriller</td>
      <td>251</td>
    </tr>
    <tr>
      <th>4</th>
      <td>Romance</td>
      <td>247</td>
    </tr>
    <tr>
      <th>5</th>
      <td>Adventure</td>
      <td>135</td>
    </tr>
    <tr>
      <th>6</th>
      <td>Childrens</td>
      <td>122</td>
    </tr>
    <tr>
      <th>7</th>
      <td>Crime</td>
      <td>109</td>
    </tr>
    <tr>
      <th>8</th>
      <td>Sci-Fi</td>
      <td>101</td>
    </tr>
    <tr>
      <th>9</th>
      <td>Horror</td>
      <td>92</td>
    </tr>
    <tr>
      <th>10</th>
      <td>War</td>
      <td>71</td>
    </tr>
    <tr>
      <th>11</th>
      <td>Mystery</td>
      <td>61</td>
    </tr>
    <tr>
      <th>12</th>
      <td>Musical</td>
      <td>56</td>
    </tr>
    <tr>
      <th>13</th>
      <td>Documentary</td>
      <td>50</td>
    </tr>
    <tr>
      <th>14</th>
      <td>Animation</td>
      <td>42</td>
    </tr>
    <tr>
      <th>15</th>
      <td>Western</td>
      <td>27</td>
    </tr>
    <tr>
      <th>16</th>
      <td>Film-Noir</td>
      <td>24</td>
    </tr>
    <tr>
      <th>17</th>
      <td>Fantasy</td>
      <td>22</td>
    </tr>
  </tbody>
</table>
</div>

In [ ]:
# Provide your answer here.

## Task 3 - Can we find movies that belong to more than one genre?

- The basic approach to finding this information is to add a new column to the movie DataFrame, which will contain the sum of 1's from the genre columns for each movie.
- After that, we can identify the number of movies with more than one genre by selecting rows where the new column has a value greater than 1.

### Task 3.1

#### Let's create a new column named `Number of Genres` and add it to the DataFrame.

#### Use the `sum()` function to calculate the number of genres for each movie and assign it to a new column named `Number of Genres`.

<div style="overflow-x:auto;">
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>movie id</th>
      <th>movie title</th>
      <th>release date</th>
      <th>Action</th>
      <th>Adventure</th>
      <th>Animation</th>
      <th>Childrens</th>
      <th>Comedy</th>
      <th>Crime</th>
      <th>Documentary</th>
      <th>...</th>
      <th>Film-Noir</th>
      <th>Horror</th>
      <th>Musical</th>
      <th>Mystery</th>
      <th>Romance</th>
      <th>Sci-Fi</th>
      <th>Thriller</th>
      <th>War</th>
      <th>Western</th>
      <th>Number of Genres</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1</td>
      <td>Toy Story</td>
      <td>1-Jan-95</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>1</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>3</td>
    </tr>
    <tr>
      <th>1</th>
      <td>2</td>
      <td>GoldenEye</td>
      <td>1-Jan-95</td>
      <td>1</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>3</td>
    </tr>
    <tr>
      <th>2</th>
      <td>3</td>
      <td>Four Rooms</td>
      <td>1-Jan-95</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
    </tr>
    <tr>
      <th>3</th>
      <td>4</td>
      <td>Get Shorty</td>
      <td>1-Jan-95</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>3</td>
    </tr>
    <tr>
      <th>4</th>
      <td>5</td>
      <td>Copycat</td>
      <td>1-Jan-95</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>3</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>1675</th>
      <td>1678</td>
      <td>Mat' i syn</td>
      <td>6-Feb-98</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
    </tr>
    <tr>
      <th>1676</th>
      <td>1679</td>
      <td>B. Monkey</td>
      <td>6-Feb-98</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>2</td>
    </tr>
    <tr>
      <th>1677</th>
      <td>1680</td>
      <td>Sliding Doors</td>
      <td>1-Jan-98</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>2</td>
    </tr>
    <tr>
      <th>1678</th>
      <td>1681</td>
      <td>You So Crazy</td>
      <td>1-Jan-94</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
    </tr>
    <tr>
      <th>1679</th>
      <td>1682</td>
      <td>Scream of Stone (Schrei aus Stein)</td>
      <td>8-Mar-96</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
    </tr>
  </tbody>
</table>
<p>1680 rows × 22 columns</p>
</div>

In [ ]:
movies["Number of Genres"] = movies[genres_list].sum(axis=1)
movies

### Task 3.2 (0.5 points)

#### Now, let's select the rows where `Number of Genres` > 1 to find the number of movies with more than one genre. Create a variable named `movies_with_multi_genres` to store the result.

<div style="overflow-x:auto;">
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>movie id</th>
      <th>movie title</th>
      <th>release date</th>
      <th>Action</th>
      <th>Adventure</th>
      <th>Animation</th>
      <th>Childrens</th>
      <th>Comedy</th>
      <th>Crime</th>
      <th>Documentary</th>
      <th>...</th>
      <th>Film-Noir</th>
      <th>Horror</th>
      <th>Musical</th>
      <th>Mystery</th>
      <th>Romance</th>
      <th>Sci-Fi</th>
      <th>Thriller</th>
      <th>War</th>
      <th>Western</th>
      <th>Number of Genres</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1</td>
      <td>Toy Story</td>
      <td>1-Jan-95</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>1</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>3</td>
    </tr>
    <tr>
      <th>1</th>
      <td>2</td>
      <td>GoldenEye</td>
      <td>1-Jan-95</td>
      <td>1</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>3</td>
    </tr>
    <tr>
      <th>3</th>
      <td>4</td>
      <td>Get Shorty</td>
      <td>1-Jan-95</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>3</td>
    </tr>
    <tr>
      <th>4</th>
      <td>5</td>
      <td>Copycat</td>
      <td>1-Jan-95</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>3</td>
    </tr>
    <tr>
      <th>6</th>
      <td>7</td>
      <td>Twelve Monkeys</td>
      <td>1-Jan-95</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>2</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>1666</th>
      <td>1669</td>
      <td>MURDER and murder</td>
      <td>20-Jun-97</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>3</td>
    </tr>
    <tr>
      <th>1667</th>
      <td>1670</td>
      <td>Tainted</td>
      <td>1-Feb-98</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>2</td>
    </tr>
    <tr>
      <th>1670</th>
      <td>1673</td>
      <td>Mirage</td>
      <td>1-Jan-95</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>2</td>
    </tr>
    <tr>
      <th>1676</th>
      <td>1679</td>
      <td>B. Monkey</td>
      <td>6-Feb-98</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>2</td>
    </tr>
    <tr>
      <th>1677</th>
      <td>1680</td>
      <td>Sliding Doors</td>
      <td>1-Jan-98</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>2</td>
    </tr>
  </tbody>
</table>
<p>849 rows × 22 columns</p>
</div>

In [ ]:
# Provide your answer here.

### Task 3.3 (0.5 points)

#### Let's print the shape of this DataFrame `movies_with_multi_genres` to determine the number of movies that have more than one genre.

(849, 22)

In [ ]:
# Provide your answer here.

## Task 4 - Can we find the genres that are most liked by users?

- As we have already observed, the information regarding ratings is present in the ratings dataset, while the genre columns are present in the movies dataset. The only column connecting these two datasets is the <code>movie id</code> column. We can merge both datasets using this common column.
- Pandas provides various functionalities for easily combining Series or DataFrames using different kinds of set logic for indexes and relational algebra functionality, such as join or merge operations.

### Task 4.1 (1 point)

#### Merge the `movies` dataset with the `ratings` dataset. Create a variable named `df_merge` and save the merged DataFrame into this variable.
#### Hint: Use `left_on='movie id'`, `right_on='movie id'` and `how='inner'` as the parameters for the merge operation.

<div style="overflow-x:auto;">
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>movie id</th>
      <th>movie title</th>
      <th>release date</th>
      <th>Action</th>
      <th>Adventure</th>
      <th>Animation</th>
      <th>Childrens</th>
      <th>Comedy</th>
      <th>Crime</th>
      <th>Documentary</th>
      <th>...</th>
      <th>Mystery</th>
      <th>Romance</th>
      <th>Sci-Fi</th>
      <th>Thriller</th>
      <th>War</th>
      <th>Western</th>
      <th>Number of Genres</th>
      <th>user id</th>
      <th>rating</th>
      <th>timestamp</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1</td>
      <td>Toy Story</td>
      <td>1-Jan-95</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>1</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>3</td>
      <td>308</td>
      <td>4</td>
      <td>887736532</td>
    </tr>
    <tr>
      <th>1</th>
      <td>1</td>
      <td>Toy Story</td>
      <td>1-Jan-95</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>1</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>3</td>
      <td>287</td>
      <td>5</td>
      <td>875334088</td>
    </tr>
    <tr>
      <th>2</th>
      <td>1</td>
      <td>Toy Story</td>
      <td>1-Jan-95</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>1</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>3</td>
      <td>148</td>
      <td>4</td>
      <td>877019411</td>
    </tr>
    <tr>
      <th>3</th>
      <td>1</td>
      <td>Toy Story</td>
      <td>1-Jan-95</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>1</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>3</td>
      <td>280</td>
      <td>4</td>
      <td>891700426</td>
    </tr>
    <tr>
      <th>4</th>
      <td>1</td>
      <td>Toy Story</td>
      <td>1-Jan-95</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>1</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>3</td>
      <td>66</td>
      <td>3</td>
      <td>883601324</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>99985</th>
      <td>1678</td>
      <td>Mat' i syn</td>
      <td>6-Feb-98</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>863</td>
      <td>1</td>
      <td>889289570</td>
    </tr>
    <tr>
      <th>99986</th>
      <td>1679</td>
      <td>B. Monkey</td>
      <td>6-Feb-98</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>...</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>2</td>
      <td>863</td>
      <td>3</td>
      <td>889289491</td>
    </tr>
    <tr>
      <th>99987</th>
      <td>1680</td>
      <td>Sliding Doors</td>
      <td>1-Jan-98</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>...</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>2</td>
      <td>863</td>
      <td>2</td>
      <td>889289570</td>
    </tr>
    <tr>
      <th>99988</th>
      <td>1681</td>
      <td>You So Crazy</td>
      <td>1-Jan-94</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>896</td>
      <td>3</td>
      <td>887160722</td>
    </tr>
    <tr>
      <th>99989</th>
      <td>1682</td>
      <td>Scream of Stone (Schrei aus Stein)</td>
      <td>8-Mar-96</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>916</td>
      <td>3</td>
      <td>880845755</td>
    </tr>
  </tbody>
</table>
<p>99990 rows × 25 columns</p>
</div>

In [ ]:
# Provide your answer here.

- To identify the genres most liked by users, we can find the average ratings for each genre and then compare them.
- Let's iterate through the merged DataFrame for the columns present in the genres list. Whenever a particular genre has a value of '1' in its column, the corresponding rating will be extracted. In the end, we will calculate the average of all these extracted ratings for each genre.

### Task 4.2

#### Let's compute the average rating for each genre.
```text
Action : 3.480245417953027
Adventure : 3.503526503308369
Animation : 3.5766990291262135
Childrens : 3.3532442216652742
Comedy : 3.3940734781442745
Crime : 3.6322780881440098
Documentary : 3.6728232189973613
Drama : 3.6873793708484772
Fantasy : 3.2152366863905324
Film-Noir : 3.9215233698788228
Horror : 3.2903893172841827
Musical : 3.521396851029471
Mystery : 3.63813155386082
Romance : 3.621704948358255
Sci-Fi : 3.5607227022780834
Thriller : 3.5090069495245064
War : 3.815811874866993
Western : 3.6132686084142396
```

In [ ]:
for one_genre in genres_list:
    print(one_genre,':' , df_merge[df_merge[one_genre]==1]["rating"].mean())

## Task 5 - Can we find which movies are most preferred by users?

#### To find out, we first need to get the average rating of each movie. We can achieve this by using the `groupby()` function from pandas.

### Task 5.1 (0.5 points)

#### Print the first 5 rows of the merged DataFrame `df_merge`.

<div style="overflow-x:auto;">
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>movie id</th>
      <th>movie title</th>
      <th>release date</th>
      <th>Action</th>
      <th>Adventure</th>
      <th>Animation</th>
      <th>Childrens</th>
      <th>Comedy</th>
      <th>Crime</th>
      <th>Documentary</th>
      <th>...</th>
      <th>Mystery</th>
      <th>Romance</th>
      <th>Sci-Fi</th>
      <th>Thriller</th>
      <th>War</th>
      <th>Western</th>
      <th>Number of Genres</th>
      <th>user id</th>
      <th>rating</th>
      <th>timestamp</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1</td>
      <td>Toy Story</td>
      <td>1-Jan-95</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>1</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>3</td>
      <td>308</td>
      <td>4</td>
      <td>887736532</td>
    </tr>
    <tr>
      <th>1</th>
      <td>1</td>
      <td>Toy Story</td>
      <td>1-Jan-95</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>1</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>3</td>
      <td>287</td>
      <td>5</td>
      <td>875334088</td>
    </tr>
    <tr>
      <th>2</th>
      <td>1</td>
      <td>Toy Story</td>
      <td>1-Jan-95</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>1</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>3</td>
      <td>148</td>
      <td>4</td>
      <td>877019411</td>
    </tr>
    <tr>
      <th>3</th>
      <td>1</td>
      <td>Toy Story</td>
      <td>1-Jan-95</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>1</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>3</td>
      <td>280</td>
      <td>4</td>
      <td>891700426</td>
    </tr>
    <tr>
      <th>4</th>
      <td>1</td>
      <td>Toy Story</td>
      <td>1-Jan-95</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>1</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>3</td>
      <td>66</td>
      <td>3</td>
      <td>883601324</td>
    </tr>
  </tbody>
</table>
<p>5 rows × 25 columns</p>
</div>

In [ ]:
# Provide your answer here.

### Task 5.2

#### Let's apply the `groupby()` function to our dataset `df_merge` and compute the average rating for each movie. Don't forget to reset the index. Create a variable named `avg_rating_df` and save the resulting DataFrame into this variable.

<div style="overflow-x:auto;">
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>movie title</th>
      <th>rating</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>'Til There Was You</td>
      <td>2.333333</td>
    </tr>
    <tr>
      <th>1</th>
      <td>1-900</td>
      <td>2.600000</td>
    </tr>
    <tr>
      <th>2</th>
      <td>101 Dalmatians</td>
      <td>2.908257</td>
    </tr>
    <tr>
      <th>3</th>
      <td>12 Angry Men</td>
      <td>4.344000</td>
    </tr>
    <tr>
      <th>4</th>
      <td>187</td>
      <td>3.024390</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>1652</th>
      <td>Young Guns</td>
      <td>3.207921</td>
    </tr>
    <tr>
      <th>1653</th>
      <td>Young Guns II</td>
      <td>2.772727</td>
    </tr>
    <tr>
      <th>1654</th>
      <td>Young Poisoner's Handbook, The</td>
      <td>3.341463</td>
    </tr>
    <tr>
      <th>1655</th>
      <td>Zeus and Roxanne</td>
      <td>2.166667</td>
    </tr>
    <tr>
      <th>1656</th>
      <td>Á köldum klaka (Cold Fever)</td>
      <td>3.000000</td>
    </tr>
  </tbody>
</table>
<p>1657 rows × 2 columns</p>
</div>

In [ ]:
avg_rating_df = df_merge.groupby(by=['movie title'])['rating'].mean().reset_index(drop=False)
avg_rating_df

### Task 5.3

#### Let's rename the `rating` column in `avg_rating_df` to `average rating` for better clarity.

<div style="overflow-x:auto;">
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>movie title</th>
      <th>average rating</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>'Til There Was You</td>
      <td>2.333333</td>
    </tr>
    <tr>
      <th>1</th>
      <td>1-900</td>
      <td>2.600000</td>
    </tr>
    <tr>
      <th>2</th>
      <td>101 Dalmatians</td>
      <td>2.908257</td>
    </tr>
    <tr>
      <th>3</th>
      <td>12 Angry Men</td>
      <td>4.344000</td>
    </tr>
    <tr>
      <th>4</th>
      <td>187</td>
      <td>3.024390</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>1652</th>
      <td>Young Guns</td>
      <td>3.207921</td>
    </tr>
    <tr>
      <th>1653</th>
      <td>Young Guns II</td>
      <td>2.772727</td>
    </tr>
    <tr>
      <th>1654</th>
      <td>Young Poisoner's Handbook, The</td>
      <td>3.341463</td>
    </tr>
    <tr>
      <th>1655</th>
      <td>Zeus and Roxanne</td>
      <td>2.166667</td>
    </tr>
    <tr>
      <th>1656</th>
      <td>Á köldum klaka (Cold Fever)</td>
      <td>3.000000</td>
    </tr>
  </tbody>
</table>
<p>1657 rows × 2 columns</p>
</div>

In [ ]:
avg_rating_df.rename(columns={'rating':'average rating'},inplace=True)
avg_rating_df

### Task 5.4 (1 point)

#### Let's check the movies with the highest average ratings.
#### Hint: Sort by `average rating`.

<div style="overflow-x:auto;">
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>movie title</th>
      <th>average rating</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>Great Day in Harlem, A</td>
      <td>5.0</td>
    </tr>
    <tr>
      <th>1</th>
      <td>Prefontaine</td>
      <td>5.0</td>
    </tr>
    <tr>
      <th>2</th>
      <td>Someone Else's America</td>
      <td>5.0</td>
    </tr>
    <tr>
      <th>3</th>
      <td>Entertaining Angels: The Dorothy Day Story</td>
      <td>5.0</td>
    </tr>
    <tr>
      <th>4</th>
      <td>Marlene Dietrich: Shadow and Light (</td>
      <td>5.0</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>1652</th>
      <td>Babyfever</td>
      <td>1.0</td>
    </tr>
    <tr>
      <th>1653</th>
      <td>Lashou shentan</td>
      <td>1.0</td>
    </tr>
    <tr>
      <th>1654</th>
      <td>Shadows (Cienie)</td>
      <td>1.0</td>
    </tr>
    <tr>
      <th>1655</th>
      <td>Shadow of Angels (Schatten der Engel)</td>
      <td>1.0</td>
    </tr>
    <tr>
      <th>1656</th>
      <td>Power 98</td>
      <td>1.0</td>
    </tr>
  </tbody>
</table>
<p>1657 rows × 2 columns</p>
</div>

In [ ]:
# Provide your answer here.

### Task 5.5 (1 point)

#### Let's filter (subset) the DataFrame to include only rows where `average rating` is equal to 5.

<div style="overflow-x:auto;">
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>movie title</th>
      <th>average rating</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>30</th>
      <td>Aiqing wansui</td>
      <td>5.0</td>
    </tr>
    <tr>
      <th>461</th>
      <td>Entertaining Angels: The Dorothy Day Story</td>
      <td>5.0</td>
    </tr>
    <tr>
      <th>631</th>
      <td>Great Day in Harlem, A</td>
      <td>5.0</td>
    </tr>
    <tr>
      <th>942</th>
      <td>Marlene Dietrich: Shadow and Light (</td>
      <td>5.0</td>
    </tr>
    <tr>
      <th>1170</th>
      <td>Prefontaine</td>
      <td>5.0</td>
    </tr>
    <tr>
      <th>1270</th>
      <td>Saint of Fort Washington, The</td>
      <td>5.0</td>
    </tr>
    <tr>
      <th>1274</th>
      <td>Santa with Muscles</td>
      <td>5.0</td>
    </tr>
    <tr>
      <th>1354</th>
      <td>Someone Else's America</td>
      <td>5.0</td>
    </tr>
    <tr>
      <th>1382</th>
      <td>Star Kid</td>
      <td>5.0</td>
    </tr>
    <tr>
      <th>1466</th>
      <td>They Made Me a Criminal</td>
      <td>5.0</td>
    </tr>
  </tbody>
</table>
</div>

In [ ]:
# Provide your answer here.

## Task 6 - Can we find which movies have been rated the most times?

To find out, we first need to get the frequency of each movie. We can achieve this by using the `groupby()` function from pandas.

### Task 6.1

#### Let's create a variable named `movie_rating_count_df` that contains the movies along with their rating counts.

<div style="overflow-x:auto;">
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>movie title</th>
      <th>rating</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>'Til There Was You</td>
      <td>9</td>
    </tr>
    <tr>
      <th>1</th>
      <td>1-900</td>
      <td>5</td>
    </tr>
    <tr>
      <th>2</th>
      <td>101 Dalmatians</td>
      <td>109</td>
    </tr>
    <tr>
      <th>3</th>
      <td>12 Angry Men</td>
      <td>125</td>
    </tr>
    <tr>
      <th>4</th>
      <td>187</td>
      <td>41</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>1652</th>
      <td>Young Guns</td>
      <td>101</td>
    </tr>
    <tr>
      <th>1653</th>
      <td>Young Guns II</td>
      <td>44</td>
    </tr>
    <tr>
      <th>1654</th>
      <td>Young Poisoner's Handbook, The</td>
      <td>41</td>
    </tr>
    <tr>
      <th>1655</th>
      <td>Zeus and Roxanne</td>
      <td>6</td>
    </tr>
    <tr>
      <th>1656</th>
      <td>Á köldum klaka (Cold Fever)</td>
      <td>1</td>
    </tr>
  </tbody>
</table>
<p>1657 rows × 2 columns</p>
</div>

In [ ]:
movie_rating_count_df = df_merge.groupby(['movie title'])["rating"].count().reset_index(drop=False)
movie_rating_count_df

### Task 6.2 (1 point)

#### Rename the `rating` column in `movie_rate_count_df` to `rating counts` and sort the DataFrame in descending order to display the highest to lowest count of ratings.

<div # Provide your answer here.>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>movie title</th>
      <th>rating counts</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>Star Wars</td>
      <td>583</td>
    </tr>
    <tr>
      <th>1</th>
      <td>Contact</td>
      <td>509</td>
    </tr>
    <tr>
      <th>2</th>
      <td>Fargo</td>
      <td>508</td>
    </tr>
    <tr>
      <th>3</th>
      <td>Return of the Jedi</td>
      <td>507</td>
    </tr>
    <tr>
      <th>4</th>
      <td>Liar Liar</td>
      <td>485</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>1652</th>
      <td>Object of My Affection, The</td>
      <td>1</td>
    </tr>
    <tr>
      <th>1653</th>
      <td>Office Killer</td>
      <td>1</td>
    </tr>
    <tr>
      <th>1654</th>
      <td>Other Voices, Other Rooms</td>
      <td>1</td>
    </tr>
    <tr>
      <th>1655</th>
      <td>Paris Was a Woman</td>
      <td>1</td>
    </tr>
    <tr>
      <th>1656</th>
      <td>Á köldum klaka (Cold Fever)</td>
      <td>1</td>
    </tr>
  </tbody>
</table>
<p>1657 rows × 2 columns</p>
</div>

In [ ]:
movie_rating_count_df.rename(columns={'rating':'rating counts'},inplace=True)
movie_rating_count_df

In [ ]:
# Provide your answer here.

## Task 7 - Can we identify a relationship between the demographic details of users and their ratings for movies?

- All the datasets need to be used to analyze the demographics of users. Therefore, we will merge all the datasets together to perform the analysis.
- Since we have already merged the `ratings` and `movies` datasets into a variable named `df_merge`, we can now merge the `users` dataset with this merged dataset.

### Task 7.1 (1 point)

#### Merging the `users` dataset with the `movies` and `ratings` datasets (The `movies` and `ratings` datasets are already merged as `df_merge`). Create a variable named `df_merge_all` and save the resulting DataFrame into this variable.

<div style="overflow-x:auto;">
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>movie id</th>
      <th>movie title</th>
      <th>release date</th>
      <th>Action</th>
      <th>Adventure</th>
      <th>Animation</th>
      <th>Childrens</th>
      <th>Comedy</th>
      <th>Crime</th>
      <th>Documentary</th>
      <th>...</th>
      <th>War</th>
      <th>Western</th>
      <th>Number of Genres</th>
      <th>user id</th>
      <th>rating</th>
      <th>timestamp</th>
      <th>age</th>
      <th>gender</th>
      <th>occupation</th>
      <th>zip code</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1</td>
      <td>Toy Story</td>
      <td>1-Jan-95</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>1</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>3</td>
      <td>308</td>
      <td>4</td>
      <td>887736532</td>
      <td>60</td>
      <td>M</td>
      <td>retired</td>
      <td>95076</td>
    </tr>
    <tr>
      <th>1</th>
      <td>1</td>
      <td>Toy Story</td>
      <td>1-Jan-95</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>1</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>3</td>
      <td>287</td>
      <td>5</td>
      <td>875334088</td>
      <td>21</td>
      <td>M</td>
      <td>salesman</td>
      <td>31211</td>
    </tr>
    <tr>
      <th>2</th>
      <td>1</td>
      <td>Toy Story</td>
      <td>1-Jan-95</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>1</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>3</td>
      <td>148</td>
      <td>4</td>
      <td>877019411</td>
      <td>33</td>
      <td>M</td>
      <td>engineer</td>
      <td>97006</td>
    </tr>
    <tr>
      <th>3</th>
      <td>1</td>
      <td>Toy Story</td>
      <td>1-Jan-95</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>1</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>3</td>
      <td>280</td>
      <td>4</td>
      <td>891700426</td>
      <td>30</td>
      <td>F</td>
      <td>librarian</td>
      <td>22903</td>
    </tr>
    <tr>
      <th>4</th>
      <td>1</td>
      <td>Toy Story</td>
      <td>1-Jan-95</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>1</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>3</td>
      <td>66</td>
      <td>3</td>
      <td>883601324</td>
      <td>23</td>
      <td>M</td>
      <td>student</td>
      <td>80521</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>99985</th>
      <td>1678</td>
      <td>Mat' i syn</td>
      <td>6-Feb-98</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>863</td>
      <td>1</td>
      <td>889289570</td>
      <td>17</td>
      <td>M</td>
      <td>student</td>
      <td>60089</td>
    </tr>
    <tr>
      <th>99986</th>
      <td>1679</td>
      <td>B. Monkey</td>
      <td>6-Feb-98</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>2</td>
      <td>863</td>
      <td>3</td>
      <td>889289491</td>
      <td>17</td>
      <td>M</td>
      <td>student</td>
      <td>60089</td>
    </tr>
    <tr>
      <th>99987</th>
      <td>1680</td>
      <td>Sliding Doors</td>
      <td>1-Jan-98</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>2</td>
      <td>863</td>
      <td>2</td>
      <td>889289570</td>
      <td>17</td>
      <td>M</td>
      <td>student</td>
      <td>60089</td>
    </tr>
    <tr>
      <th>99988</th>
      <td>1681</td>
      <td>You So Crazy</td>
      <td>1-Jan-94</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>896</td>
      <td>3</td>
      <td>887160722</td>
      <td>28</td>
      <td>M</td>
      <td>writer</td>
      <td>91505</td>
    </tr>
    <tr>
      <th>99989</th>
      <td>1682</td>
      <td>Scream of Stone (Schrei aus Stein)</td>
      <td>8-Mar-96</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>916</td>
      <td>3</td>
      <td>880845755</td>
      <td>27</td>
      <td>M</td>
      <td>engineer</td>
      <td>N2L5N</td>
    </tr>
  </tbody>
</table>
<p>99990 rows × 29 columns</p>
</div>

In [ ]:
# Provide your answer here.

### Task 7.2 (1 point)

#### Group the df_merge_all dataset by the `gender` column and compute the average rating within each group.

<div style="overflow-x:auto;">
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>gender</th>
      <th>average rating</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>F</td>
      <td>3.531510</td>
    </tr>
    <tr>
      <th>1</th>
      <td>M</td>
      <td>3.529333</td>
    </tr>
  </tbody>
</table>
</div>

In [ ]:
# Provide your answer here.

### Task 7.3 (1 point)

#### Group the df_merge_all dataset by the occupation column and compute the average rating within each group.

<div style="overflow-x:auto;">
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>occupation</th>
      <th>average rating</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>administrator</td>
      <td>3.635646</td>
    </tr>
    <tr>
      <th>1</th>
      <td>artist</td>
      <td>3.653380</td>
    </tr>
    <tr>
      <th>2</th>
      <td>doctor</td>
      <td>3.688889</td>
    </tr>
    <tr>
      <th>3</th>
      <td>educator</td>
      <td>3.670692</td>
    </tr>
    <tr>
      <th>4</th>
      <td>engineer</td>
      <td>3.541473</td>
    </tr>
    <tr>
      <th>5</th>
      <td>entertainment</td>
      <td>3.440783</td>
    </tr>
    <tr>
      <th>6</th>
      <td>executive</td>
      <td>3.349794</td>
    </tr>
    <tr>
      <th>7</th>
      <td>healthcare</td>
      <td>2.896220</td>
    </tr>
    <tr>
      <th>8</th>
      <td>homemaker</td>
      <td>3.301003</td>
    </tr>
    <tr>
      <th>9</th>
      <td>lawyer</td>
      <td>3.735316</td>
    </tr>
    <tr>
      <th>10</th>
      <td>librarian</td>
      <td>3.560781</td>
    </tr>
    <tr>
      <th>11</th>
      <td>marketing</td>
      <td>3.485641</td>
    </tr>
    <tr>
      <th>12</th>
      <td>none</td>
      <td>3.777778</td>
    </tr>
    <tr>
      <th>13</th>
      <td>other</td>
      <td>3.552335</td>
    </tr>
    <tr>
      <th>14</th>
      <td>programmer</td>
      <td>3.568205</td>
    </tr>
    <tr>
      <th>15</th>
      <td>retired</td>
      <td>3.466750</td>
    </tr>
    <tr>
      <th>16</th>
      <td>salesman</td>
      <td>3.582944</td>
    </tr>
    <tr>
      <th>17</th>
      <td>scientist</td>
      <td>3.611273</td>
    </tr>
    <tr>
      <th>18</th>
      <td>student</td>
      <td>3.515167</td>
    </tr>
    <tr>
      <th>19</th>
      <td>technician</td>
      <td>3.532097</td>
    </tr>
    <tr>
      <th>20</th>
      <td>writer</td>
      <td>3.376152</td>
    </tr>
  </tbody>
</table>
</div>

In [ ]:
# Provide your answer here.

### Task 7.4 (1 point)

#### Group the `df_merge_all` dataset by `gender` and `occupation` and compute the average rating within each group.

<div style="overflow-x:auto;">
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>gender</th>
      <th>occupation</th>
      <th>average rating</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>F</td>
      <td>administrator</td>
      <td>3.781839</td>
    </tr>
    <tr>
      <th>1</th>
      <td>F</td>
      <td>artist</td>
      <td>3.347065</td>
    </tr>
    <tr>
      <th>2</th>
      <td>F</td>
      <td>educator</td>
      <td>3.699132</td>
    </tr>
    <tr>
      <th>3</th>
      <td>F</td>
      <td>engineer</td>
      <td>3.751724</td>
    </tr>
    <tr>
      <th>4</th>
      <td>F</td>
      <td>entertainment</td>
      <td>3.448889</td>
    </tr>
    <tr>
      <th>5</th>
      <td>F</td>
      <td>executive</td>
      <td>3.773756</td>
    </tr>
    <tr>
      <th>6</th>
      <td>F</td>
      <td>healthcare</td>
      <td>2.736021</td>
    </tr>
    <tr>
      <th>7</th>
      <td>F</td>
      <td>homemaker</td>
      <td>3.278810</td>
    </tr>
    <tr>
      <th>8</th>
      <td>F</td>
      <td>lawyer</td>
      <td>3.623188</td>
    </tr>
    <tr>
      <th>9</th>
      <td>F</td>
      <td>librarian</td>
      <td>3.580070</td>
    </tr>
    <tr>
      <th>10</th>
      <td>F</td>
      <td>marketing</td>
      <td>3.522624</td>
    </tr>
    <tr>
      <th>11</th>
      <td>F</td>
      <td>none</td>
      <td>3.632877</td>
    </tr>
    <tr>
      <th>12</th>
      <td>F</td>
      <td>other</td>
      <td>3.531114</td>
    </tr>
    <tr>
      <th>13</th>
      <td>F</td>
      <td>programmer</td>
      <td>3.577566</td>
    </tr>
    <tr>
      <th>14</th>
      <td>F</td>
      <td>retired</td>
      <td>3.239437</td>
    </tr>
    <tr>
      <th>15</th>
      <td>F</td>
      <td>salesman</td>
      <td>3.870206</td>
    </tr>
    <tr>
      <th>16</th>
      <td>F</td>
      <td>scientist</td>
      <td>3.251799</td>
    </tr>
    <tr>
      <th>17</th>
      <td>F</td>
      <td>student</td>
      <td>3.602879</td>
    </tr>
    <tr>
      <th>18</th>
      <td>F</td>
      <td>technician</td>
      <td>3.268519</td>
    </tr>
    <tr>
      <th>19</th>
      <td>F</td>
      <td>writer</td>
      <td>3.663986</td>
    </tr>
    <tr>
      <th>20</th>
      <td>M</td>
      <td>administrator</td>
      <td>3.555233</td>
    </tr>
    <tr>
      <th>21</th>
      <td>M</td>
      <td>artist</td>
      <td>3.875841</td>
    </tr>
    <tr>
      <th>22</th>
      <td>M</td>
      <td>doctor</td>
      <td>3.688889</td>
    </tr>
    <tr>
      <th>23</th>
      <td>M</td>
      <td>educator</td>
      <td>3.660246</td>
    </tr>
    <tr>
      <th>24</th>
      <td>M</td>
      <td>engineer</td>
      <td>3.537676</td>
    </tr>
    <tr>
      <th>25</th>
      <td>M</td>
      <td>entertainment</td>
      <td>3.439807</td>
    </tr>
    <tr>
      <th>26</th>
      <td>M</td>
      <td>executive</td>
      <td>3.320340</td>
    </tr>
    <tr>
      <th>27</th>
      <td>M</td>
      <td>healthcare</td>
      <td>3.639839</td>
    </tr>
    <tr>
      <th>28</th>
      <td>M</td>
      <td>homemaker</td>
      <td>3.500000</td>
    </tr>
    <tr>
      <th>29</th>
      <td>M</td>
      <td>lawyer</td>
      <td>3.741379</td>
    </tr>
    <tr>
      <th>30</th>
      <td>M</td>
      <td>librarian</td>
      <td>3.537920</td>
    </tr>
    <tr>
      <th>31</th>
      <td>M</td>
      <td>marketing</td>
      <td>3.474801</td>
    </tr>
    <tr>
      <th>32</th>
      <td>M</td>
      <td>none</td>
      <td>3.876636</td>
    </tr>
    <tr>
      <th>33</th>
      <td>M</td>
      <td>other</td>
      <td>3.563447</td>
    </tr>
    <tr>
      <th>34</th>
      <td>M</td>
      <td>programmer</td>
      <td>3.567674</td>
    </tr>
    <tr>
      <th>35</th>
      <td>M</td>
      <td>retired</td>
      <td>3.477243</td>
    </tr>
    <tr>
      <th>36</th>
      <td>M</td>
      <td>salesman</td>
      <td>3.394584</td>
    </tr>
    <tr>
      <th>37</th>
      <td>M</td>
      <td>scientist</td>
      <td>3.637311</td>
    </tr>
    <tr>
      <th>38</th>
      <td>M</td>
      <td>student</td>
      <td>3.484440</td>
    </tr>
    <tr>
      <th>39</th>
      <td>M</td>
      <td>technician</td>
      <td>3.540477</td>
    </tr>
    <tr>
      <th>40</th>
      <td>M</td>
      <td>writer</td>
      <td>3.180770</td>
    </tr>
  </tbody>
</table>
</div>

In [ ]:
# Provide your answer here.

### Task 7.5 (1 point)

#### Please provide insights between demographic details and ratings.

Provide your answer here.

## Task 8 - Executive summary

### Task 8.1 (1.5 points)
####Please provide an executive summary of the analysis of these datasets. Your summary should cover all the questions you answered above. Use Python comments to provide the summary.

Provide your answer here.