## Context
A tip is a monetary incentive given by customers or guests for polite, prompt, and efficient service provided by the staff. The practice of tipping has existed for a long time and has become particularly common in service industries such as hotels and restaurants.

## Objective

Chef's Kitchen is one of the most popular restaurants in San Diego, serving as a one-stop destination for food lovers. The polite and efficient service provided by the restaurant staff often earns them tips from customers. As a Data Analyst for the restaurant, you have been tasked with analyzing the provided data to identify patterns and trends in revenue and tips received from customers across various demographics. Additionally, you are expected to create informative visualizations to convey the insights obtained from the analysis. <br>
<br>
The dataset contains the following features:

- order_id: A unique identifier for each order.
- day: The day of the week when the customer visited the restaurant (Thu, Fri, Sat, or Sun).
- time: The time of day when the customer visited the restaurant (Lunch or Dinner).
- size: The number of people present at the table.
- smoker: Whether the table included smokers (No: The table did not include smokers, Yes: The table included smokers).
- sex: The gender of the person who paid the bill (Male or Female).
- total_bill: The total bill amount in dollars.
- tip: The tip amount in dollars.

Let’s first import the necessary libraries before starting our analysis.

There are two options for this assignment.

### Option 1

For this assignment, you can simply run the provided code for **Option 1** to get started. You do not need to download the data file `Tips.csv` and upload it to your Google Drive.

If you choose this option, you can skip the steps for:

* Connecting to Google Drive
* Setting the current folder

### Option 2

If you prefer, you may download the data file `Tips.csv`, upload it to your Google Drive, connect Google Colab to your Google Drive, and set the appropriate current folder.

This option is also acceptable. If you choose this approach, you may need to delete or modify the provided code in for **Option 1**.

## Importing the libraries

In [ ]:
# Mount your drive
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
# Change current directory
%cd "/content/drive/MyDrive/Colab Notebooks/ANLY2500/HW/path of the new directory"

In [ ]:
 # Verify the current directory
%pwd

In [ ]:
 # Verify the current directory
%ls

In [2]:
# Libraries for reading and manipulating data
import numpy as np
import pandas as pd

# Libraries for data visualization
import matplotlib.pyplot as plt

Let’s now load the dataset.

## Load the dataset
## Option 1 Code

In [3]:
tips_df = pd.read_csv("https://juxinglongsuuta.github.io/anly2500/Tips.csv")

## Task 1
Overview of the dataset

The initial steps to get an overview of the dataset are to:

- Observe the first few rows to verify that the dataset has been loaded correctly.
- Get information about the number of rows and columns.
- Check the data types of the columns to ensure that data is stored in the correct format and values are as expected.
- Review the statistical summary to gain an overview of the numerical columns."

### Task 1.1 (0.5 points)

Let's display the first 5 rows of the dataset to ensure it was loaded correctly.

<div style="overflow-x:auto;">
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>order_id</th>
      <th>day</th>
      <th>time</th>
      <th>size</th>
      <th>smoker</th>
      <th>sex</th>
      <th>total_bill</th>
      <th>tip</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1</td>
      <td>Sun</td>
      <td>Dinner</td>
      <td>2</td>
      <td>No</td>
      <td>Female</td>
      <td>16.99</td>
      <td>1.01</td>
    </tr>
    <tr>
      <th>1</th>
      <td>2</td>
      <td>Sun</td>
      <td>Dinner</td>
      <td>3</td>
      <td>No</td>
      <td>Male</td>
      <td>10.34</td>
      <td>1.66</td>
    </tr>
    <tr>
      <th>2</th>
      <td>3</td>
      <td>Sun</td>
      <td>Dinner</td>
      <td>3</td>
      <td>No</td>
      <td>Male</td>
      <td>21.01</td>
      <td>3.50</td>
    </tr>
    <tr>
      <th>3</th>
      <td>4</td>
      <td>Sun</td>
      <td>Dinner</td>
      <td>2</td>
      <td>No</td>
      <td>Male</td>
      <td>23.68</td>
      <td>3.31</td>
    </tr>
    <tr>
      <th>4</th>
      <td>5</td>
      <td>Sun</td>
      <td>Dinner</td>
      <td>4</td>
      <td>No</td>
      <td>Female</td>
      <td>24.59</td>
      <td>3.61</td>
    </tr>
  </tbody>
</table>
</div>

In [ ]:
# Provide your answer here. (0.5 points)

In [ ]:
# Please provide your insights on the result above in the cell below.

Please provide your insights here.

- The dataset contains information about customers visiting the restaurant.
- It includes details about the day and time of their visit, along with information about their bill and tip amounts.

### Task 1.2  (1.5 points)

Let's understand the shape of the dataset by checking the number of rows and columns.
```text
(244, 8)
```

In [ ]:
# Provide your answer here.  (0.5 points)

In [ ]:
# Please provide your insights on the result above in the cell below. (1 point)

Please provide your insights here.

###  Task 1.3 (1.5 points)

Check the data types of the columns in the dataset.

```text
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   order_id    244 non-null    int64  
 1   day         244 non-null    object
 2   time        244 non-null    object
 3   size        244 non-null    int64  
 4   smoker      244 non-null    object
 5   sex         244 non-null    object
 6   total_bill  244 non-null    float64
 7   tip         244 non-null    float64
dtypes: float64(2), int64(2), object(4)
memory usage: 15.4+ KB
```

In [ ]:
# Provide your answer here. (0.5 points)

In [ ]:
# Please provide your insights on the result above in the cell below. (1 point)

Please provide your insights here.

###  Task 1.4 (1.5 points)

Let's drop the `order_id` column from our dataset, as it will not add any value to our analysis since it is a unique identifier.

In [ ]:
tips_df.drop('order_id', axis=1, inplace=True)

Let's print the first few rows of the dataset `tips_df` to verify that the `order_id` column has been successfully dropped.

<div>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>day</th>
      <th>time</th>
      <th>size</th>
      <th>smoker</th>
      <th>sex</th>
      <th>total_bill</th>
      <th>tip</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>Sun</td>
      <td>Dinner</td>
      <td>2</td>
      <td>No</td>
      <td>Female</td>
      <td>16.99</td>
      <td>1.01</td>
    </tr>
    <tr>
      <th>1</th>
      <td>Sun</td>
      <td>Dinner</td>
      <td>3</td>
      <td>No</td>
      <td>Male</td>
      <td>10.34</td>
      <td>1.66</td>
    </tr>
    <tr>
      <th>2</th>
      <td>Sun</td>
      <td>Dinner</td>
      <td>3</td>
      <td>No</td>
      <td>Male</td>
      <td>21.01</td>
      <td>3.50</td>
    </tr>
    <tr>
      <th>3</th>
      <td>Sun</td>
      <td>Dinner</td>
      <td>2</td>
      <td>No</td>
      <td>Male</td>
      <td>23.68</td>
      <td>3.31</td>
    </tr>
    <tr>
      <th>4</th>
      <td>Sun</td>
      <td>Dinner</td>
      <td>4</td>
      <td>No</td>
      <td>Female</td>
      <td>24.59</td>
      <td>3.61</td>
    </tr>
  </tbody>
</table>
</div>

In [ ]:
# Provide your answer here. (0.5 points)

In [ ]:
# Please provide your insights on the result above in the cell below. (1 point)

Please provide your insights here.

###  Task 1.5 (1.5 points)

Get the statistical summary of the dataset.

<div style="overflow-x:auto;">
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>size</th>
      <th>total_bill</th>
      <th>tip</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>count</th>
      <td>244.000000</td>
      <td>244.000000</td>
      <td>244.000000</td>
    </tr>
    <tr>
      <th>mean</th>
      <td>2.569672</td>
      <td>19.785943</td>
      <td>2.998279</td>
    </tr>
    <tr>
      <th>std</th>
      <td>0.951100</td>
      <td>8.902412</td>
      <td>1.383638</td>
    </tr>
    <tr>
      <th>min</th>
      <td>1.000000</td>
      <td>3.070000</td>
      <td>1.000000</td>
    </tr>
    <tr>
      <th>25%</th>
      <td>2.000000</td>
      <td>13.347500</td>
      <td>2.000000</td>
    </tr>
    <tr>
      <th>50%</th>
      <td>2.000000</td>
      <td>17.795000</td>
      <td>2.900000</td>
    </tr>
    <tr>
      <th>75%</th>
      <td>3.000000</td>
      <td>24.127500</td>
      <td>3.562500</td>
    </tr>
    <tr>
      <th>max</th>
      <td>6.000000</td>
      <td>50.810000</td>
      <td>10.000000</td>
    </tr>
  </tbody>
</table>
</div>

In [ ]:
# Provide your answer here. (0.5 points)

In [ ]:
# Please provide your insights on the result above in the cell below. (1 point)

Please provide your insights here.

##  Task 2

Now that we have a preliminary understanding of the dataset, let's explore the distribution of each column for better insight. We'll start with the numerical columns and use `hist()` to visualize their distributions.

### Task 2.1 (1 point)

Understand the distribution of `total_bill`.

<img  width="400"  src=''/>

In [ ]:
plt.hist(tips_df['total_bill'],bins=10)

In [ ]:
# Please provide your insights on the result above in the cell below. (1 point)

Please provide your insights here.

### Task 2.2 (2 points)

Understand the distribution of `tip`

<img  width="400"  src=''/>

In [ ]:
# Provide your answer here. (1 point)

In [ ]:
# Please provide your insights on the result above in the cell below. (1 point)

Please provide your insights here.

###  Task 2.3 (2 points)

Understand the distribution of `size`

<img width="400"  src=''/>

In [ ]:
# Provide your answer here. (1 point)

In [ ]:
# Please provide your insights on the result above in the cell below. (1 point)

Please provide your insights here.

##  Task 3

We have now explored the distribution of the numerical columns. Next, let's move on to the categorical columns and use bar charts to visualize their distribution.

### Task 3.1
Understand the distribution of `day`

<div style="overflow-x:auto;">
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>count</th>
    </tr>
    <tr>
      <th>day</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>Sat</th>
      <td>87</td>
    </tr>
    <tr>
      <th>Sun</th>
      <td>76</td>
    </tr>
    <tr>
      <th>Thur</th>
      <td>62</td>
    </tr>
    <tr>
      <th>Fri</th>
      <td>19</td>
    </tr>
  </tbody>
</table>
</div>

In [ ]:
vc = tips_df["day"].value_counts()
vc

```text
Index(['Sat', 'Sun', 'Thur', 'Fri'], dtype='object', name='day')
```

In [ ]:
vc.index

```text
array([87, 76, 62, 19])
```

In [ ]:
vc.values

<img width="400"  src=''/>

In [ ]:
plt.bar(vc.index,vc.values)

Please provide your insights on the result above in the cell below.

Please provide your insights here.

- There are more orders during the weekends than on weekdays.
- The highest number of orders is received on Saturdays.

### Task 3.2 (2 points)
Understand the distribution of `time`

<div style="overflow-x:auto;">
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>count</th>
    </tr>
    <tr>
      <th>time</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>Dinner</th>
      <td>176</td>
    </tr>
    <tr>
      <th>Lunch</th>
      <td>68</td>
    </tr>
  </tbody>
</table>
</div>

In [ ]:
# Provide your answer here. (0.5 points)

<img width="400"  src=''/>

In [ ]:
# Provide your answer here. (0.5 points)

In [ ]:
# Please provide your insights on the result above in the cell below. (1 point)

Please provide your insights here.

### Task 3.3 (2 points)
Understand the distribution of `sex`

<div style="overflow-x:auto;">
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>count</th>
    </tr>
    <tr>
      <th>time</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>Dinner</th>
      <td>176</td>
    </tr>
    <tr>
      <th>Lunch</th>
      <td>68</td>
    </tr>
  </tbody>
</table>
</div>

In [ ]:
# Provide your answer here. (0.5 points)

<img width="400"  src=''/>

In [ ]:
# Provide your answer here. (0.5 points)

In [ ]:
# Please provide your insights on the result above in the cell below. (1 point)

Please provide your insights here.

### Task 3.4 (2 points)
Understand the distribution of `smoker`

<div  style="overflow-x:auto;">
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>count</th>
    </tr>
    <tr>
      <th>smoker</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>No</th>
      <td>151</td>
    </tr>
    <tr>
      <th>Yes</th>
      <td>93</td>
    </tr>
  </tbody>
</table>
</div>

In [ ]:
# Provide your answer here. (0.5 points)

<img  width="400"  src=''/>

In [ ]:
# Provide your answer here. (0.5 points)

In [ ]:
# Please provide your insights on the result above in the cell below. (1 point)

Please provide your insights here.

## Task 4
Up to this point, we have explored the distribution of individual columns. Now, let's examine the relationships between various columns to identify meaningful patterns and trends. We’ll use scatter plots to visualize the relationships between the numerical columns.

### Task 4.1 (2.5 points)
Understand the relationship between `total_bill` and `tip` using a scatter plot.

<img  width="400"  src=''/>

In [ ]:
# Provide your answer here. (1.5 points)

In [ ]:
# Please provide your insights on the result above in the cell below. (1 point)

Please provide your insights here.